### ISSUE TITLE
Runtime error with WebJobs.Extensions.CosmosDB in console app for .NET Framework 4.8

### ISSUE THREAD

**Issue by benpap24** [Azure/azure-webjobs-sdk#2690] opened 2021-04-05 18:48 UTC
I receive the following runtime error when configuring webjobs with cosmosdb:
```
MissingMethodException: Method not found: 'Microsoft.Azure.Documents.Client.ConnectionPolicy Microsoft.Azure.Documents.ChangeFeedProcessor.DocumentCollectionInfo.get_ConnectionPolicy()'.
```

#### Repro steps

Empty console project, for a .NET 4.8, and add latest relevant libraries.

**1. Set up the host builder, with `build.AddCosmosDB()`**

My code example:
```
IHostBuilder hostBuilder = new HostBuilder()
               .UseEnvironment("Development")
               .ConfigureAppConfiguration((hostContext, config) => {
                   config.AddJsonFile("appsettings.json", optional: true);
                   config.AddEnvironmentVariables();
               })
               .ConfigureWebJobs(builder => {
                   builder.AddExecutionContextBinding();
                   builder.AddAzureStorageCoreServices();
                   builder.AddCosmosDB();
               })
               .ConfigureLogging((context, builder) => {
                   // add logging for debug
                   builder.AddConsole();
               });

using (IHost host = hostBuilder.Build())
{
    await host.RunAsync();
}
```
You can add the connection string to the builder instead of the Trigger if you want. 
 
**2. Set up the CosmosDBTrigger with the correct information.**

I used the example code:  

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=csharp

With my relevant information.

Please note, setting this up you will run into:
https://github.com/Azure/azure-webjobs-sdk-extensions/issues/573

We are using Webjobs V3 (thus azure functions V2), therefore we want to use the CosmosDB extension not the DocumentDb extension recommended in the above link.

However, by setting an alias on the documentdb.core we are able to circumvent this issue.

Also, if you added the connection string to the builder, you do not need to include it with the Trigger.

**3. With everything set up correctly, you will be able to start the code. When starting the code you receive the below stack:**

```
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException
  HResult=0x80131500
  Message=Error indexing method 'CosmosTrigger'
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
   at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 81
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__17.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 94
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<CreateAsync>d__16.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 97
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<GetAsync>d__15.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexProvider.cs:line 69
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<Create>d__21.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\JobHostContextFactory.cs:line 108
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<InitializeHostAsync>d__35.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 347
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__21.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 95
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LogicAppWebJob.Program.<Main>d__0.MoveNext() in C:\src\Willowglade\Testing\LogicAppWebJob\LogicAppWebJob\Program.cs:line 52

Inner Exception 1:
MissingMethodException: Method not found: 'Microsoft.Azure.Documents.Client.ConnectionPolicy Microsoft.Azure.Documents.ChangeFeedProcessor.DocumentCollectionInfo.get_ConnectionPolicy()'.
```

#### Expected behavior

It should be listening to the CosmosDb changefeed, and no errors should occur.

#### Actual behavior

Receive a runtime error.

#### Known workarounds

None at the moment.

#### Related information 

Provide any related information 

* The latest version of all relevant packages.

**Comment by v-anvari** [comment] 2021-04-08 11:21
Thank you @benpap24, We will be looking into the issue and update you with our findings

Tagging @ealsur / @fabiocav , for more inputs

**Comment by ealsur** [comment] 2021-04-08 17:39
The issue is that when on a NET Framework application, the WebJobs.CosmosDB package has only NET Standard 2.0 dependencies:

![image](https://user-images.githubusercontent.com/1633401/114071308-d352e780-9855-11eb-8317-0eb05163500c.png)

Which includes the Change Feed Processor package AND `Microsoft.Azure.DocumentDB.Core`.

But the Change Feed Processor has a conditional dependency:

![image](https://user-images.githubusercontent.com/1633401/114071569-1d3bcd80-9856-11eb-9175-f2ca851c0657.png)

So when running on NET Framework (not a Function App project template but a NET FX Console) you get 2 dependencies for the SDK loaded (`Microsoft.Azure.DocumentDB` and `Microsoft.Azure.DocumentDB.Core`) and that might be source of the problem.

The only solution I could think of is if the Webjobs.CosmosDB extension could be multi-targetted.

Luckily, the new version of the Webjobs.CosmosDB extension being worked on (https://github.com/Azure/azure-webjobs-sdk-extensions/pull/717) just uses a single package, so it will fix this issue.

**Comment by v-anvari** [comment] 2021-04-12 14:03
Thank you Mathias, 

@benpap24, Let us know if the information resolves your query, or if you have any further queries.

**Comment by benpap24** [comment] 2021-04-13 22:03
@v-anvari, The information allowed us to get it to start working. Thanks.

**Comment by fabiocav** [comment] 2021-04-13 22:49
Thank you for the update. Closing as resolved, but let us know if you need any additional information.

**Closed as completed by fabiocav** 2021-04-13 22:49 UTC

**Comment by cloudsere** [comment] 2021-05-01 03:27
Hi, if I understand it right, by now we still cannot use `Microsoft.Azure.WebJobs.Extensions.CosmosDB` for net461, since the PR is not merged yet, right? @fabiocav 
Can you share how did you solve the problem ? @benpap24

**Comment by ealsur** [comment] 2021-05-03 14:19
@cloudsere The PR is still in progress and when merged, it will be a whole new major version of the extension. When the new version is released in the upcoming months, it would solve the dependency issue because it uses other packages altogether.

**Comment by benpap24** [comment] 2021-05-03 19:27
> Hi, if I understand it right, by now we still cannot use `Microsoft.Azure.WebJobs.Extensions.CosmosDB` for net461, since the PR is not merged yet, right? @fabiocav
> Can you share how did you solve the problem ? @benpap24

As a temporary workaround we changed the reference of the two libraries and found a combination that functioned correctly. You should have access of both of these when downloaded the packages from nuget.

We changed ChangeFeedProcessor to **netstandard2.0**:
```
FROM:
Microsoft.Azure.DocumentDB.ChangeFeedProcessor.2.3.2\lib\net45\Microsoft.Azure.Documents.ChangeFeedProcessor.dll
TP:
Microsoft.Azure.DocumentDB.ChangeFeedProcessor.2.3.2\lib\netstandard2.0\Microsoft.Azure.Documents.ChangeFeedProcessor.dll
```

and we changed Microsoft.Azure.DocumentDB to **net45**:
```
FROM:
Microsoft.Azure.DocumentDB.2.13.1\lib\net461\Microsoft.Azure.Documents.Client.dll
TO:
Microsoft.Azure.DocumentDB.2.13.1\lib\net45\Microsoft.Azure.Documents.Client.dll
```

We did not have to change Microsoft.Azure.DocumentDB.Core, and am still using **netstandard1.6**

Should this have worked? I'm not 100% sure, but fortunately we were lucky and everything does function correctly.

**Comment by cloudsere** [comment] 2021-05-06 06:31
@benpap24 Hi, thanks for your reply.
We are using a `.csproj` for our net461 project, I add `<PackageReference Include="Microsoft.Azure.DocumentDB" Version="2.0.0" ExcludeAssets="All" />` and all the warnings of namespace conflicts went away, however, we cannot build this project, it will stuck and never ends
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <Platform>x64</Platform>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.14" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.12.0" />
    <PackageReference Include="Microsoft.Azure.DocumentDB" Version="2.0.0" ExcludeAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
</Project>

```
