### ISSUE TITLE
Incorrect Web Hook URL

### ISSUE THREAD

**Issue by ms-v-csacha** [Azure/azure-webjobs-sdk#2738] opened 2021-06-22 19:05 UTC
When using a triggered Web Job deployed in Azure, the provided Web Hook URL in the WebJob properties is incorrect.

#### Repro steps

1. Create ASP.NET web app project and add a WebJob in visual studio (tested in VS2019). No additional content or modifications needed.

2. Deploy to Azure (existing App Service Plan or new).

3. Navigate to deployed Azure resource, open WebJobs page, and view WebJob properties.

4. Copy Web Hook URL, Username, and Password. 

5. Make a POST request with basic authentication (tested in Postman) with the copied credentials and Web Hook URL.

6. Receive Status: 404 Not Found response

Note that the provided Web Hook URL ends in /start. Photos around the web show the URL ending in /run

For example, in my test application:

https://webapplication220210621095220.scm.azurewebsites.net/api/triggeredwebjobs/WebJob1/start

VS.

https://webapplication220210621095220.scm.azurewebsites.net/api/triggeredwebjobs/WebJob1/run

#### Expected behavior

Correct Web Hook URL displayed in the copiable Web Hook section of the WebJob properties.

#### Actual behavior

Incorrect Web Hook URL displayed

#### Known workarounds

Web Hook URL can be used successfully by changing the URL ending to /run.

**Comment by v-anvari** [comment] 2021-06-24 11:35
Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment] 2021-06-25 14:05
Hi @ms-v-csacha , I tried to reproduce it with the above steps in vs 19. What is the web app template that you are using, is it  ASP.NET MVC or  ASP.NET web app. Because with this template, I get error while creating webjob, that its not allowed to create a webjob.

**Comment by ms-v-csacha** [comment] 2021-06-25 16:27
Hi @v-anvari,

I'm using the template named: "ASP.NET Web Application (.NET Framework)"

It's further down the list, but it's my understanding that the .NET Core versions don't permit web jobs. I'll send you a screenshot of it over Teams.

**Comment by v-anvari** [comment] 2021-07-05 11:48
Hi @ms-v-csacha , Apologies for the delayed response, I could reproduce the above steps, but I could run the WebHook URL with success code. I used a continuous triggered WebJob in my case, and ASP is P1V2. Can you try once again and let us know if it is still not working for you. Can you also tell me the configurations if it is still giving you 404 error

![image](https://user-images.githubusercontent.com/66122429/124466687-7b744000-ddb4-11eb-8289-d47bf799b655.png)

**Comment by ms-v-csacha** [comment] 2021-07-09 22:49
Hello @v-anvari,

I just redeployed with my project and still getting the same issue. Here are the templates from the resource deployment as well as the deployed project. Let's have a screenshare session next week for demonstrating the issue and showing the complete steps I'm taking to reach that point!

https://github.com/ms-v-csacha/Azure_azure-webjobs-sdk_issues_2738_repro

[Deployment-Microsoft.Web-WebApp-Portal-b031171d-8cda.zip](https://github.com/Azure/azure-webjobs-sdk/files/6794190/Deployment-Microsoft.Web-WebApp-Portal-b031171d-8cda.zip)

[ExportedTemplate-Microsoft.Web-ASP-Portal-5eea853a-baf4.zip](https://github.com/Azure/azure-webjobs-sdk/files/6794191/ExportedTemplate-Microsoft.Web-ASP-Portal-5eea853a-baf4.zip)

**Comment by v-anvari** [comment] 2021-07-13 13:00
Hi @ms-v-csacha , yes sure, please send me a mail on your availability

**Comment by v-anvari** [comment] 2021-11-08 15:19
Closing this issue as there is no further activity, please feel free to reach out to us in case of any further queries

**Closed as completed by v-anvari** 2021-11-08 15:19 UTC
