### ISSUE TITLE
Blob binding expression to servicebus trigger property no longer works

### ISSUE THREAD

**Issue by mliesmons** [Azure/azure-webjobs-sdk#2403] opened 2020-01-15 06:51 UTC
Please see also https://github.com/Azure/azure-functions-servicebus-extension/issues/44#issue-545396362

This is a real blocking issue and makes upgrading for us imposible.

**Comment by tomgallard** [comment] 2020-01-23 14:01
I think this is also related to:

https://github.com/Azure/azure-functions-servicebus-extension/issues/48
https://github.com/Azure/azure-functions-servicebus-extension/issues/52

**Comment by alrod** [comment] 2020-03-10 23:17
the issue is fixed in https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.1

**Closed as completed by alrod** 2020-03-10 23:18 UTC

**Comment by mliesmons** [comment] 2020-03-11 09:03
Great, POCO binding works again, tnx.
