### ISSUE TITLE
Table binding definitions not parsed into function.json

### ISSUE THREAD

**Issue by kgoderis** [Azure/azure-webjobs-sdk#1785] opened 2018-07-02 14:04 UTC
Table bindings defined in C# Azure functions are not parsed and added to function.json

#### Repro steps

1. Create a new Azure function on VS Code, using a Blob Trigger, with runtime = beta, language = C#
2. Copy the code from Example 1 on https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table

```
public class TableStorage
{
    public class MyPoco
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public string Text { get; set; }
    }

    [FunctionName("TableInput")]
    public static void TableInput(
        [QueueTrigger("table-items")] string input, 
        [Table("MyTable", "MyPartition", "{queueTrigger}")] MyPoco poco, 
        TraceWriter log)
    {
        log.Info($"PK={poco.PartitionKey}, RK={poco.RowKey}, Text={poco.Text}");
    }
}
```

3. Build the project, or start debugging
4. The generated function.json looks like

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.14",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "queueTrigger",
      "queueName": "table-items",
      "name": "input"
    }
  ],
  "disabled": false,
  "scriptFile": "<not relevant>",
  "entryPoint": "<not relevant>.TableStorage.TableInput"
}
```

#### Expected behavior

function.json should include a binding definition for the Table binding

#### Known workarounds

AFAIK none, as function.json is parsed/overwritten at every compile cycle

#### Environment

[Visual Studio Code 1.24.1]
[Azure Functions Core Tools (2.0.1-beta.31)]
[Function Runtime Version: 2.0.11888.0]
[Microsoft.NET.Sdk.Functions: 1.0.14]
[Microsoft.Azure.WebJobs : 3.0.0-beta5]

.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by brettsam** [comment] 2018-07-06 17:38
This is by design -- the `"configurationSource": "attributes"` tells the Functions runtime to get all of the details from the function itself, rather than from the function.json.

I'll close this as by-design. Please re-open if you are running into issues with your scenarios.

**Closed by brettsam** 2018-07-06 17:38 UTC

**Comment by kgoderis** [comment] 2018-07-07 14:45
@brettsam So you say that this is by design for Table bindings, but not for any other type of Binding? that does not make sense. In the generated function.json the binding for the QueueTrigger is included, but not for the Table. So, something is wrong with the json generator, no?

**Comment by brettsam** [comment] 2018-07-09 13:29
We generate *Trigger* metadata in that file, but nothing else. That's because the Functions Scale Controller (which has the logic for scaling out) needs to read trigger metadata so it can monitor the trigger source for scaling purposes. But for input and output bindings, the host handles that by reading the function's attributes at runtime.

Here's a little background: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#autogenerated-functionjson, but it doesn't mention that we only generate trigger metdata in that file (although it is mentioned briefly here: https://blogs.msdn.microsoft.com/appserviceteam/2017/08/14/azure-functions-tools-released-for-visual-studio-2017-update-3/). 

I'll submit a change to the docs to get that clarified.

**Comment by brettsam** [comment] 2018-07-09 13:32
Oh, I didn't read well enough :-) That document actually does mention this already -- 

> The purpose of this file is to provide information to the scale controller to use for scaling decisions on the consumption plan. For this reason, the file only has trigger info, not input or output bindings.
