### ISSUE TITLE
EventHub credential cache should be based on namespace+eventhub, not just eventhub

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#1374] opened 2017-10-10 15:52 UTC
We had an issue arise where a customer had two EventHubTrigger functions targeting different connection strings, but the same EventHub name. This caused one of them to never connect (without error -- it was successfully connecting to the wrong namespace but the leases were already taken).

We need to discriminate based on more than the EventHubName so this collision doesn't happen.

There is a workaround:

Trigger1: 
- Set the EventHubName as you'd expect.

Trigger2:
- Set the EventHubName to something random -- this will create a separate entry for the credentials.
- Use ConnectionString with EntityPath set to the correct EventHub -- the EntityPath on the connection string takes precendence so we'll choose the right pieces if you do this.

**Comment by paulbatum** [comment] 2017-11-08 22:40
duplicate of https://github.com/Azure/azure-webjobs-sdk/issues/1086

**Closed by paulbatum** 2017-11-08 22:40 UTC
Labels: bug
