### ISSUE TITLE
Support newer version (6.1+) of WindowsAzure.Storage

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-webjobs-sdk#679] opened 2016-03-29 21:17 UTC
I'd like to use the [DataMovement library] (https://www.nuget.org/packages/Microsoft.Azure.Storage.DataMovement) (an API version of AzCopy) to download blobs quickly, but it requires a newer version of the storage library which is currently incompatible with the WebJobs SDK.
DataMovement dependency:
WindowsAzure.Storage (>= 6.1.0)
WebJobs dependency:
WindowsAzure.Storage (>= 4.3.0 && <= 5.0.2)

**Comment by mathewc** [comment] 2016-03-29 22:08
See https://github.com/Azure/azure-webjobs-sdk/issues/631 for some relevant details. The latest prerelease package has the version cap removed.

Closing this bug, since it is a dupe of https://github.com/Azure/azure-webjobs-sdk/issues/565.

**Closed by mathewc** 2016-03-29 22:08 UTC

**Comment by davidmatson** [comment] 2016-03-29 22:32
Ah, thanks. I searched but forgot to check closed issues.

**Comment by mathewc** [comment] 2016-04-22 23:57
Update: we've just released version 1.1.2 of the SDK on Nuget.org. This version is a hotfix to 1.1.1 that removes the Storage version cap that we had in place. So if you upgrade to 1.1.2 you should now be unblocked to upgrade to later storage versions. You should be fine upgrading to 6.2 - I did a test pass on that and it looked good. I haven't tried 7.0 yet.

**Comment by mathewc** [comment] 2016-07-15 01:00
FYI: We've released the [2.0.0-beta1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.0.0-beta1) prerelease on Nuget. In this version, we've moved completely to the latest Storage SDK version.
