### ISSUE TITLE
Azure Runtime - StrongNames not always skipped when running 64-bit webjob

### ISSUE THREAD

**Issue by brandondahler** [Azure/azure-webjobs-sdk#1668] opened 2018-04-18 03:49 UTC
When running an instance of a webjob that uses a delay signed library, depending on the publicKey being delay signed and the preferred bitness of the executable, the application may receiving a "Strong name validation failed." error.

I'll preface the rest by saying that I'm not sure this is the correct repository to report this in because I believe this has more to do with the runtime details of Azure's App Service than the webjobs SDK.

### Repro steps

**Specific**
1. Clone https://github.com/brandondahler/AzureWebJobs-StrongNameVerificationSkipping-bug
2. Build and deploy StrongNameVerificationSkipping.WebJob64 to Azure App Service as a webjob

**Generic**
1. Create .NET Console project
2. Unset "prefer 32-bit"
3. Reference a delay-signed assembly that uses Microsoft's publicKey (such as a self-built version of EntityFramework)
4. Update program to force it to load that assembly at runtime -- simply referencing any type, function, property will do.
5. Deploy to Azure App Service as a webjob

### Expected behavior

Application does not crash with "Strong name validation failed." error.  

Expected behavior can be seen by deploying StrongNameVerificationSkipping.WebJob from the specific reproduction steps above:

```
[04/18/2018 03:08:19 > 270fc7: SYS INFO] Run script 'StrongNameVerificationSkipping.WebJob.exe' with script host - 'WindowsScriptHost'
[04/18/2018 03:08:19 > 270fc7: SYS INFO] Status changed to Running
[04/18/2018 03:08:20 > 270fc7: INFO] Is64Bit: False
[04/18/2018 03:08:20 > 270fc7: INFO] StaticFunction.Example called.
[04/18/2018 03:08:20 > 270fc7: SYS INFO] Status changed to Success
```

### Actual behavior

Application crashes with "Strong name validation failed." error:

```
[04/18/2018 03:08:19 > 270fc7: SYS INFO] Run script 'StrongNameVerificationSkipping.WebJob64.exe' with script host - 'WindowsScriptHost'
[04/18/2018 03:08:19 > 270fc7: SYS INFO] Status changed to Running
[04/18/2018 03:08:20 > 270fc7: ERR ] 
[04/18/2018 03:08:20 > 270fc7: ERR ] Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'StrongNameVerificationSkipping.DelayedSign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
[04/18/2018 03:08:20 > 270fc7: ERR ]    --- End of inner exception stack trace ---
[04/18/2018 03:08:20 > 270fc7: ERR ]    at StrongNameVerificationSkipping.WebJob64.Program.Main()
[04/18/2018 03:08:20 > 270fc7: SYS ERR ] Job failed due to exit code -532462766
```

### Known workarounds

Checking "Prefer 32-bit" on compilation of webjob executable prevents behavior.

### Related information 

1. Reproduction repository: https://github.com/brandondahler/AzureWebJobs-StrongNameVerificationSkipping-bug
2. I tested this with my own signing key and it did not appear to have the same issue.  It is possible the error could be related to using the publicKeyToken b77a5c561934e089; however, I believe the inconsistency between the two bitness execution modes still constitutes a bug.

**Comment by paulbatum** [comment] 2018-04-18 18:07
Not a high impact issue and a valid workaround exists. Thanks for the report but I'm going to close this as won't-fix.

**Closed by paulbatum** 2018-04-18 18:07 UTC

**Comment by brandondahler** [comment] 2018-04-19 21:44
Is there a more appropriate place to report this issue?  The lack of consistency is worrying for future-proofing purposes -- can I actually rely on the workaround continuing to work for production-level applications?

Additionally, the workaround is sub-optimal particularly for applications that require running in 64-bit mode.

**Comment by paulbatum** [comment] 2018-04-19 21:47
Apologies, I wasn't very clear. By workaround I meant signing the assemblies yourself (you mentioned the issue did not repro with your own signing key).

**Comment by paulbatum** [comment] 2018-04-19 21:54
Also you are probably correct that the issue is not specific to webjobs and is really just about the app service infrastructure. But I don't really have any recommendations on where to file the issue, sorry.
