### ISSUE TITLE
Will this ever come out of Beta?

### ISSUE THREAD

**Issue by smurfster** [Azure/azure-webjobs-sdk#1534] opened 2018-01-24 16:12 UTC
I was wondering if this package will ever come out of Beta as my place of work deems this as a high risk for live environments?

**Comment by mathewc** [comment] 2018-01-25 17:55
Duplicate of https://github.com/Azure/azure-webjobs-sdk/issues/1512. See discussion there.

**Closed by mathewc** 2018-01-25 17:55 UTC

**Comment by mathewc** [comment] 2018-01-26 22:43
Release 2.1 of core SDK and Extensions is now up on Nuget.
