### ISSUE TITLE
Poison blob queue message in multi storage account scenario

### ISSUE THREAD

**Issue by Fabian-Schmidt** [Azure/azure-webjobs-sdk#804] opened 2016-08-30 02:21 UTC
Hi,
I have setup two storage accounts in the connectionStrings. First one is setup as `AzureWebJobsStorage` and a second as `AzureWebJobsMyToken`.

In the second account a blob trigger is configured via an attribute on the class `[StorageAccount("MyToken")]`.
In case this blob trigger fails multiple times a poison blob message is generated in the queue `webjobs-blobtrigger-poison` of the first storage account.
My expectation was that the same storage account, as used for the trigger, is used for the poison message.

Thanks,
Fabian

**Comment by mathewc** [comment] 2016-08-30 03:28
Thanks for reporting. What version of the SDK are you using?

**Comment by Fabian-Schmidt** [comment] 2016-08-30 03:51
Microsoft.Azure.WebJobs Version 1.1.2.0
Microsoft.Azure.WebJobs.Extensions Version 1.0.1.0
Microsoft.Azure.WebJobs.Host Version 1.1.2.0

**Comment by mamaso** [comment] 2016-09-13 22:50
@christopheranderson @mathewc Unfortunately this scenario and #797 are basically incompatible (if we add the poison queue to the secondary storage account it cannot be a blob-only storage account).

Which issue do you guys want to prioritize?

**Comment by lindydonna** [comment] 2016-09-14 01:21
@mamaso We were thinking of excluding blob only storage accounts for RC, since it requires perf testing as well. Does that simplify the decision?

**Comment by mathewc** [comment] 2016-09-14 04:45
@mamaso My thought was that the control queue we use for poison blobs would live in the primary storage account, since it is an internal implementation detail of blob triggers. That's the same place the trigger queue we create lives.

**Comment by mamaso** [comment] 2016-09-14 17:33
Yep, I think it's fine for the primary storage account to have all the queues.  Perhaps the answer is to document the poison queue behavior better since this didn't match the user's expectation of where it would be created.

**Comment by mamaso** [comment] 2016-09-20 17:34
Closing this. the current behavior is by design.

**Comment by mathewc** [comment] 2016-09-20 17:45
What is our behavior for poison queues for QueueTrigger functions in the context of secondary storage accounts? We want to ensure that we have a consistent story.

**Comment by mamaso** [comment] 2016-09-20 17:53
Just tested, QueueTrigger will create the poison queue in the secondary account, so there's some inconsistency here.

**Comment by mathewc** [comment] 2016-09-20 17:57
Yeah, that's what I thought. We'll need to drive towards a consistent model for all of these.

**Comment by mathewc** [comment] 2016-09-26 18:03
The start of a fix is in a branch I just pushed [blobfix](https://github.com/Azure/azure-webjobs-sdk/tree/blobfix). I will resume that work when I have time - the fix needs more improvements.

**Comment by mathewc** [comment] 2017-01-06 01:13
Fixed in https://github.com/Azure/azure-webjobs-sdk/commit/56b5302dda3ff6d671fb7e4c1b9ddcce0594a9a2. By default the poison queue will no be colocated in the account where the blob container lives. This is configurable via `JobJostConfiguration.Blobs.CentralizedPoisonQueue`.

**Closed by mathewc** 2017-01-06 01:13 UTC
Labels: bug, rc:should-have
