### ISSUE TITLE
Webjobs.Extensions.Servicebus fails to start at localhost

### ISSUE THREAD

**Issue by HaiyueChen** [Azure/azure-webjobs-sdk#2283] opened 2019-07-29 12:06 UTC
#### Repro steps

1. Create new Azure function service bus queue project in VS2019

2. Run the template project generated by VS2019 at localhost

#### Expected behavior

The application starts as usual

#### Actual behavior
![image](https://user-images.githubusercontent.com/40335150/62046937-780bcd80-b209-11e9-892a-59653ad282cf.png)
![image](https://user-images.githubusercontent.com/40335150/62046966-8ce86100-b209-11e9-829b-10f478751103.png)
![image](https://user-images.githubusercontent.com/40335150/62047023-b1443d80-b209-11e9-9fa8-b867ca052dc5.png)

Problem with versions 3.0.*

**Comment by paulbatum** [comment] 2019-08-02 22:05
So there are a few different issues interacting here. 

If I follow your steps as written, it is expected that the application will not work correctly, because you did not provide a service bus connection string. When you build locally you should see:
![image](https://user-images.githubusercontent.com/10663/62400902-c553ac00-b535-11e9-90d7-61939b729949.png)

When you run, you should see the following message in the console:
```
[8/2/2019 9:57:23 PM] A host error has occurred
[8/2/2019 9:57:23 PM] Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string '' is missing or empty.
```

You can fix this by adding a service bus connection string to your local.settings.json file and then referencing it in the attribute. For example if you call it 'ServiceBusConnection' then you'd update your attribute like so:

`[ServiceBusTrigger("myqueue", AccessRights.Manage, Connection = "ServiceBusConnection")] `

Now I mentioned before there are several issues here. The problem is that instead of seeing the error message I pasted above, VS is showing the "the host has not yet started" error. This is happening due to an issue with debug builds being published, which is being addressed in [this upcoming release](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12612).

Closing this as answered, feel free to comment if you have any additional questions.

**Closed as completed by paulbatum** 2019-08-02 22:05 UTC
