### ISSUE TITLE
High amount of failed dependencies on azure-webjobs-hosts blob storage

### ISSUE THREAD

**Issue by lrspublicdev** [Azure/azure-webjobs-sdk#1215] opened 2017-07-03 07:52 UTC
When running a continuous web job, having Application Insights enabled I see a huge amount of failed dependencies (404). Part of this is a request to queue storage, listening for control messages for the dashboard. But most of them are against blob storage. It is about 300000 failed request per week.
The failed request is against this resource:
storageaccount.blob.core.windows.net/appname/azure-webjobs-hosts

Is this normal? I can filter these out of Application Insights, but I'd rather not cover up a actual problem.

#### Repro steps

Create a continuous web job that listens on a Azure Storage Queue, and post messages on that queue.
Make sure AzureWebJobsStorage and AzureWebJobsDashboard are set to the same storage account.
Provide the steps required to reproduce the problem

I can create a reproducible example if this behavior is not expected.

#### Expected behavior

No failed requests against the blob storage

#### Actual behavior

See above

#### Known workarounds

Create a filter in Application Insights to ignore the 404 errors.

#### Related information 

Microsoft.Azure.WebJobs = 2.0.0
WindowsAzure.Storage = 7.2.1
Microsoft.ApplicationInsights = 2.3.0

**Comment by brettsam** [comment] 2017-07-03 16:50
Yes, this is likely normal. In the background, WebJobs does a lot of polling, and some of those return 404s, which simply tells us there's no work to do. Those queue failures are definitely known -- we listen for a queue message on a specific queue, but that queue only exists if you use the dashboard to kill the host. So for most people, that queue is nonexistent, meaning you get a 404 with every poll.

Can you share the exact failure for blobs? My guess is that it's something similar.
 
Curious -- how are you wiring up App Insights dependencies? This massive wave of dependency telemetry that you get with the default dependency tracking is one of the reasons that we haven't enabled this by default yet. I'm currently working through designs to see what makes the most sense. At some point in the future, I hope to have all of the dependencies filter-able (i.e. you can say you don't care about any host-level stuff).

**Comment by steinmr** [comment] 2017-08-17 13:31
Hi, I'm OP (I just used the wrong account for the original issue). I've been on vacation, sorry for the delay.

Not sure what exact data you need for the failure, but I retrieved this from AppInsights;

Dependency type Azure blob
Base name xxx.blob.core.windows.net
Client IP address 52.178.41.0
Cloud role instance RD00155D806xxx
Cloud role name xxx
Country or region Netherlands
Dependency duration 2,18 s
Dependency Id ZrwGVJMJ3bI=
Dependency name xxx/azure-webjobs-hosts
City Amsterdam
Device type PC
Event time 17.8.2017, 15:07:09
Result code 404
Sample Rate 20
SDK version rddf:2.3.0-1223
State or province North Holland
Successful call false
Telemetry type dependency

As for wiring it up, I have added our ApplicationInsights.config file as an attachment.
Additionally we have the following element in App.config

  <system.diagnostics>
    <trace autoflush="true" indentsize="0">
      <listeners>
        <add name="myAppInsightsListener" type="Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener" />
      </listeners>
    </trace>
  </system.diagnostics>

Additionally we do new up a new TelemetryClient to do custom events.

[ApplicationInsights.config.txt](https://github.com/Azure/azure-webjobs-sdk/files/1231362/ApplicationInsights.config.txt)

Thank you for your help and let me know if you need any other information.

**Comment by mathewc** [comment] 2017-08-17 17:30
Related to https://github.com/Azure/azure-webjobs-sdk/issues/770

**Comment by brettsam** [comment] 2017-08-17 19:51
#770 is the underlying cause of what you're seeing. It's a background operation that's very apparent when App Insights starts logging all of your storage operations.

There's not much we can do automatically to turn these off for you. App Insights is automatically logging them and isn't aware that they aren't really failures. Since you are controlling your own TelemetryClient, you may be able to:

1. Wire up a new `TelemetryInitializer` that looks specifically for these `DependencyTelemetry` items that match the 'azure-webjobs-hosts' name and mark them as success.
2. Wire up a new `TelemetryProcessor` and completely remove matching `DependencyTelemetry` from your App Insights pipeline.

We're still investigating ways to make this work automatically (with nicer filtering), so stay tuned to #1208 for updates.

**Comment by steinmr** [comment] 2017-08-18 07:29
Ok, I'll subscribe to #1208 

I think the TelemetryProcessor option seems best, so I added the following to my code. Seems to work well on my machine. It might be helpful for others.

ApplicationInsights.config file:
```xml
<TelemetryProcessors>
  <Add Type="LRS.ReceiptService.ReceiptApiWebJob.WebJobInternalErrorsFilter, ReceiptApiWebJob"/>
</TelemetryProcessors>
```

```csharp
public class WebJobInternalErrorsFilter : ITelemetryProcessor
{
    private ITelemetryProcessor Next { get; }
    public WebJobInternalErrorsFilter(ITelemetryProcessor next)
    {
        Next = next;
    }

    public void Process(ITelemetry item)
    {
        if (FilterOut(item)) { return; }
         Next.Process(item);
    }

    private static bool FilterOut(ITelemetry item)
    {
        var dep = item as DependencyTelemetry;
        if (dep == null) return true;
            
        var isInternalError = !(dep.Success ?? false) &&
                              dep.ResultCode == "404" &&
                              dep.Type == "Http" &&
                              (dep.Name?.Contains("/azure-webjobs-host") ?? false);
        return isInternalError;
   }
}
```

**Comment by brettsam** [comment] 2017-08-18 13:11
Thanks @steinmr -- that's exactly what I had in mind. If I see others hitting this, I'll refer them back here.

**Comment by steinmr** [comment] 2017-08-30 11:56
I've updated my code. My previous version only checked for Type="Http". This works fine when using the Storage Simulator locally, because the simulated Queue and Blob storage dependency telemetry are all mapped to Http. But after my excellent tester tested this against actual Azure storage, the filter did not work. So I added checking for the actual types as well.

A complete (?) list of dependency types can be found here: https://github.com/Microsoft/ApplicationInsights-Home/wiki/Dependency-types-generated-by-AppInsights-processing-pipeline

I also changed the filter to be case-insensitive just in case AppInsights decide to change casing on these telemetry instances.

**Comment by erick-thompson** [comment] 2018-01-23 23:05
I'm not sure if this belongs here, or in a new issue, but it is becoming a problem.

As we've attached Application Insights to our WebJobs, they are reporting a **huge** number of storage failures. These include a number of "container already exists" and "queue does not exist" errors. This ends up spamming the Application Insight error and dependency logging, and makes it really hard to see actual errors. It would be really nice if the WebJob SDK would use a pattern that does not result in storage exceptions, or on the wiki/docs explain how to configure Application Insights to ignore the errors.

**Comment by tbertenshaw** [comment] 2018-02-03 20:16
Seems like this issue has been around for over a year? Is there not a resolution for it? Debugging your webjob and its constant exceptions.

**Comment by erick-thompson** [comment] 2018-02-03 22:44
There isn't a resolution, except to create the queue at application startup so you don't get the mess of exceptions. That isn't a bad solution, but unless you know why it's happening, all you get is the storage exception with a lovely async callstack.

**Comment by tbertenshaw** [comment] 2018-02-03 22:48
Sorry I'm confused it seems your saying there is no solution to debugging a webjob without exceptions being thrown? Surely this is a bad experience? At least if we got the name of the queue in the exception we could create it.

**Comment by erick-thompson** [comment] 2018-02-03 23:02
The problem is that during any run of the web job, if you have Application Insights (or any other exception recording system) installed it will record each storage exception. As a result, you see thousands of storage exceptions, which make it hard to see if there are any legit exceptions (i.e., ones from user code). 

Also, if you turn on break of uncaught thrown exceptions for storage exceptions (which I need to do fairly often), it really becomes unusable, as you won't likely ever get to your exception, and only break on the web job queue exception.

There is a workaround, which is to create the queue manually. But, because the queue is it looking for differs by host, so you need to do it in code. Not too hard, but there is no documentation, and due to the storage exception data, no way to discover the queue that you need to create without looking through the sdk source code.

The fix would be to create the queue if it doesn't exist, or at least catch the exception and eat it. 

Does this make sense?

**Comment by tbertenshaw** [comment] 2018-02-03 23:06
Kind of (I'm not using app insights) kill the error by testing rather than throwing, Or create or supply the error name so the queue can be created. These would all be significantly better options IMO. 

Cheers

**Comment by erick-thompson** [comment] 2018-02-03 23:22
Either of those options would work. It's the non-discoverability that really makes this issue hurt.

**Comment by mathewc** [comment] 2018-02-04 02:13
I've pulled https://github.com/Azure/azure-webjobs-sdk/issues/770 from backlog so we can take another look at triage. While these exceptions are being handled by us internally (they result from optimistic polling) I agree that we can likely make simple changes to make them go away completely.

**Comment by mathewc** [comment] 2018-02-13 18:04
https://github.com/Azure/azure-webjobs-sdk/pull/1572 ensures that we no longer query non-existent queues. Leaving this open for @brettsam to investigate potential AI telemetry improvements to handle any remaining non-error events that AI might still log (e.g. from `CloudQueue.ExistsAsync` checks that return false).

**Comment by mathewc** [comment] 2018-08-01 22:04
@paulbatum @brettsam I think we should close this issue since we've addressed fixed the issue on our side. Nothing more we can do here really. Agree?

**Comment by paulbatum** [comment] 2018-08-01 23:08
Makes sense to me.

**Closed** 2018-08-01 23:09 UTC
