### ISSUE TITLE
Webjobs with service bus triggers become zombie when you regenerate Service Bus SAS token.

### ISSUE THREAD

**Issue by ajayaldo** [Azure/azure-webjobs-sdk#1402] opened 2017-10-25 22:26 UTC
I have webjob with ServiceBusTrigger in the function.cs pointing to a subscription. Things works fine, it processes the message from the subcription. I was expecting a running webjob to throw exception when I regenerate the primary key which is used to create the service bus config during the start up of webjob. I expect the webjob to throw 401. The problem here is, webjob continuously runs but it does not respond or methods in functions with ServiceBusTrigger attribute does not get invoked for any new messages in queue or topic post 20 minutes regenerating the service bus key. When a storage or dashboard connection string become invalid, it throws the error. Why is servicebus thing not having the same behaviour.
#### Repro steps

Provide the steps required to reproduce the problem

1. Step A
Create a method in Functions.cs    
eg: public async Task ProcessQueueMessage([ServiceBusTrigger("TestTopicName", "TestSubscriptionFilter")] BrokeredMessage message){
Console.Writeline("Yay);
}
2. Step B
Regenerate the key
#### Expected behavior
I expect a 401 either in the functions.cs or in the program.cs

#### Actual behavior

The functions class method still process messages for around 20 minutes, after that it becomes non responsive.

#### Known workarounds
Create a client and implement my current logic in OnMessage .

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by christopheranderson** [comment] 2017-11-01 18:30
Dupe of #1400

**Closed by christopheranderson** 2017-11-01 18:30 UTC
Labels: bug
