### ISSUE TITLE
QueueTrigger appears to be broke with Microsoft.NET.Sdk.Functions 1.0.19

### ISSUE THREAD

**Issue by cResults** [Azure/azure-webjobs-sdk#1889] opened 2018-09-07 13:14 UTC
below is my Azure Function that worked with 1.0.14

```csharp

        [FunctionName("LaunchTenantListener")]
        public static async Task Run([QueueTrigger(Constants.Queue, Connection = Constants.StorageConnection)]string tenantID, [Inject] PollQueuesForTenant pollQueuesForTenant)
        {
            await pollQueuesForTenant.Execute(tenantID);
        }
```
I'm currently getting this error.
```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Input string '5c61b624-567e-433e-a28c-8b044430f087' is not a valid number. Path '', line 1, position 36.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.Azure.WebJobs.Host.Protocols.JsonSerialization.ParseJObject(String json) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Protocols\JsonSerialization.cs:line 102
   at Microsoft.Azure.WebJobs.Host.Queues.QueueCausalityManager.GetOwner(CloudQueueMessage msg) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\QueueCausalityManager.cs:line 55

```
Since our code wasn't anywhere in the stack trace I changed the message that was being posted to the queue to a number and now I get

```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Microsoft.Azure.WebJobs.Host.Protocols.JsonSerialization.ParseJObject(String json) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Protocols\JsonSerialization.cs:line 102
   at Microsoft.Azure.WebJobs.Host.Queues.QueueCausalityManager.GetOwner(CloudQueueMessage msg) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\QueueCausalityManager.cs:line 55

```

Also, can you please point me to the proper place for me to post that my local storage no longer appears in Cloud Explorer?

Thank you for an amazing product that in continuously getting more awesome.

**Comment by cResults** [comment] 2018-09-07 13:53
I created an object with a single string property and posted it to the storage queue and the QueueTrigger works with that.  This is a work around that one shouldn't need to do.  Please make it better.

**Comment by nzthiago** [comment] 2018-09-12 06:48
We have also run into this today; even though you declare the queue trigger object as a string, the webjobs sdk is trying to json parse it, and it throws a Newtonsoft.Json.JsonReaderException on this line:
https://github.com/Azure/azure-webjobs-sdk/blob/b798412ad74ba97cf2d85487ae8479f277bdd85c/src/Microsoft.Azure.WebJobs.Protocols/JsonSerialization.cs#L102

**Comment by wely** [comment] 2018-09-12 06:57
I ran into similar issue. Here're the screenshots:
![screenshot1](https://user-images.githubusercontent.com/1658657/45407435-fcaa3780-b69b-11e8-89fc-cb9f81093946.JPG)

![screenshot2](https://user-images.githubusercontent.com/1658657/45407479-1b103300-b69c-11e8-986a-9a18d8a96e9f.JPG)

**Comment by JuanKRuiz** [comment] 2018-09-19 00:44
Hi guys! I'm dealing with the same on v 1.0.21 , and the main problem is that if you're using the `QueueTrigguer `to get the `PartitionKey `or `RowKey `for a `Table ` /Storage/ binding everything gets broken.


```
        [FunctionName("DeployTeamsConfiguration" )]
        public static void Run(
            [QueueTrigger(TEAMS_TASK_QUEUE)]
            string teamTask,
            [Table(TEAM_TASK_TABLE, "TeamsTask", "{queueTrigger}")]
            TeamsConfiguration teamsConfig)
```

**Comment by mathewc** [comment] 2018-09-19 21:28
Guys - I believe you're just seeing first chance exceptions in the debugger. The queue trigger does do a try/parse generating exceptions, but we handle those. Can you guys confirm that if you F5 past this error the function actually works as intended? If so, then you just need to change your VS exception settings to ignore these.

**Comment by jeffhollan** [comment] 2018-09-19 21:37
Yes I hit this sometimes too. Will keep on eye on what this could be but for mitigation if you unclick this it will stop bothering you. 

![workaround](https://user-images.githubusercontent.com/7132626/45783044-8c5e6180-bc19-11e8-86ee-0686e484ab06.png)

**Comment by nzthiago** [comment] 2018-09-20 03:27
Should it even try parse if the object type is set to string?

**Comment by JuanKRuiz** [comment] 2018-09-20 03:34
> Guys - I believe you're just seeing first chance exceptions in the debugger. The queue trigger does do a try/parse generating exceptions, but we handle those. Can you guys confirm that if you F5 past this error the function actually works as intended? If so, then you just need to change your VS exception settings to ignore these.

yes I've used that as mitigation.

**Comment by JuanKRuiz** [comment] 2018-09-20 16:48
> Should it even try parse if the object type is set to string?

Yes, the exceptions are jumping everytime the queued message doesn't match a json object.

**Comment by rasmuschristensen** [comment] 2018-09-21 13:04
Just ran into this issue too. Posting a json formatted string into the queue removes the exception and If I use a Type as the message, its also serialized correctly.  Still sees it as a pain that the exception is thrown

**Comment by jeffhollan** [comment] 2018-09-22 14:35
@paulbatum this seems to be picking up steam. Not sure if something reverted in latest VS bits? I see this on both my machines that have VS 2017 15.9.0 Preview 2.0

**Comment by superjulius** [comment] 2018-09-27 09:29
Also noticed it with SDK 3.0 while it was not the case with 2.x. I understood that the underlying exception was indeed handled by the SDK but still annoying and confusing to get such errors while debugging.

Would be great if this was not surfacing at all and as @nzthiago said, should it even try to deserialize and handle exception if the type is string. Might not be that easy to detect though...

**Comment by mathewc** [comment] 2018-09-27 18:48
PR https://github.com/Azure/azure-webjobs-sdk/pull/1930 is out to address this

**Comment by paulbatum** [comment] 2018-09-29 00:50
The PR is now merged. For users to get this fix we'll need to release an updated build of the Microsoft.Azure.WebJobs.Extensions.Storage NuGet package and then users will have to grab the update. The package should be published by mid October.

**Comment by mathewc** [comment] 2018-10-08 21:59
Closing because this has been fixed.

**Closed by mathewc** 2018-10-08 21:59 UTC

**Comment by ksoakellho** [comment] 2018-10-14 09:55
Hi @paulbatum, do you by any chance, have a release date for this package?

**Comment by paulbatum** [comment] 2018-10-15 22:54
@ksoakellho should be within the next two weeks.

**Comment by JohnReeson** [comment] 2018-10-18 08:14
Work with latest v3.0.1 Microsoft.Azure.WebJobs.Extensions.Storage, no exception is thrown.
