### ISSUE TITLE
Rename AzureFunctionsLogTable default table name

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#843] opened 2016-09-23 18:17 UTC
Link to source [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Logging/LogFactory.cs#L40)

This is a core SDK logging feature and is not Functions specific. I suggest AzureWebJobsHostLog or something similar.

**Comment by lindydonna** [comment] 2016-09-26 22:34
Duplicate of #832

**Closed by lindydonna** 2016-09-26 22:34 UTC
Labels: Breaking change
