### ISSUE TITLE
Adding UserSecretsId breaks Startup/IWebJobsBuilder

### ISSUE THREAD

**Issue by et1975** [Azure/azure-webjobs-sdk#2508] opened 2020-06-04 17:24 UTC
Otherwise working function stops invoking registered `IWebJobsStartup` class once `UserSecretsId` element is added to the project file.

#### Repro steps

1. Take a .NET function with a working startup/IWebJobsStartup class registered.
1. Add `UserSecretsId` element to any of the project file's `PropertyGroup`.
1. Run `func host start`
1. Invoke the functionality that depends on the startup working.

Observe it failing.
 
#### Expected behavior

Registered startup code should keep working. 
If there is a good reason it should not then attempting to run the function should clearly state that it's not possible. 

#### Actual behavior

It is no longer invoked. 

#### Known workarounds

Use `local.settings.json` instead to keep secrets.

#### Related information 

Provide any related information 

* Package version: Microsoft.NET.Sdk.Functions Version="3.0.3"
* SDK: 3.1.300

**Comment by v-anvari** [comment] 2021-06-17 12:21
Hi @et1975 , Apologies for the delayed response. On Azure, you are able to configure your settings directly in the application settings of your web app. This overrides the settings of your config file. This is because user secrets are read from the app settings. But, while working locally, there is a SecretManager tool, provided by the .NET Core SDK (Microsoft.Extensions.SecretManager.Tools), which you can access with the dotnet CLI.

To use the SecretManager tool, you need to add that tool in the "Tools" section of your project.json

Be sure you have a userSecretsId in your project.json. With this ID the SecretManager tool assigns the user secrets to your app. But, if you create a new ASP.NET Core project with Visual Studio, the SecretManager tool is already added.

You need to add the NuGet package Microsoft.Extensions.Configuration.UserSecrets 1.0.0 in your project.json and add builder.AddUserSecrets(). The Extension Method AddUserSecrets() loads the secret information of that project into the ConfigurationBuilder. If the keys of the secrets are equal to the keys in the previously defined appsettings.json, the app settings will be overwritten.

You can also type dotnet user-secrets --help to see more information about the existing commands.

This method is useful only for test environments. For production, it is always good to use Key vault. 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#register-services

https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#using-aspnet-core-user-secrets

Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue

**Comment by et1975** [comment] 2021-06-17 12:29
Please re-open as this answer does not address the problem I outlined. I know how function settings work, I also know how local secrets work and why one would use KeyVault in production.
What I'm saying is there's a problem when one tries to use local secrets with a function. 
Please re-read the "Expected  behavior" section.

**Comment by v-anvari** [comment] 2021-06-17 14:07
Hi @et1975 , Please provide the repro steps in detail with the code that you are trying, we shall reproduce to understand if any configuration is missing.

**Closed as completed** 2021-06-29 14:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
