### ISSUE TITLE
Configurable timer schedule / Support for custom scheduler in functions

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-webjobs-sdk#1655] opened 2018-04-05 16:14 UTC
I am using the TimerTrigger within a pre-compiled azure function and so am using the cron string value to set the timer schedule.

e.g.
`public static async Task Run([TimerTrigger("0 */5 * * * *)] TimerInfo myTimer)`

I have a requirement to change the timer schedule at runtime (e.g. by changing an application setting), but there doesn't seem to be any support for this. As far as I can see I would need to change the hard-coded string, recompile and redeploy.

I noticed that there is a constructor for the TimerTrigger attribute that accepts a Type parameter, so created a custom TimerSchedule that reads a cron expression from an environment variable and then uses the CronSchedule class with that.

e.g.
`public static async Task Run([TimerTrigger(typeof(ConfigurableCronSchedule))] TimerInfo myTimer)`

BUT, when I build the function app I get this error:

> System.NotImplementedException: Property 'ScheduleType' on attribute 'TimerTriggerAttribute' is not supported in Azure Functions.
>    at MakeFunctionJson.AttributeExtensions.CheckIfPropertyIsSupported(String attributeName, PropertyInfo property)
>    at MakeFunctionJson.AttributeExtensions.ToJObject(Attribute attribute)
>    at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at MakeFunctionJson.MethodInfoExtensions.ToFunctionJson(MethodInfo method, String assemblyPath)
>    at MakeFunctionJson.FunctionJsonConverter.<GenerateFunctions>d__9.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
>    at MakeFunctionJson.FunctionJsonConverter.TryRun()

#### Repro steps

Compile function with TimerTrigger attribute with custom TimerSchedule in constructor.

#### Expected behavior

I want to be able to configure the cron string via application setting or use my own custom scheduler type.

#### Actual behavior

Compilation exception

#### Known workarounds

None

#### Related information 

C# pre-compiled function.
Function SDK 1.0.11
WebJobs SDK 2.1.0

**Comment by paulbatum** [comment] 2018-04-18 17:36
Yep, closing as dupe of #1577

**Closed by paulbatum** 2018-04-18 17:36 UTC
