### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.EventGrid v 2.1.0 binding issue

### ISSUE THREAD

**Issue by melvincanafranca** [Azure/azure-webjobs-sdk#2711] opened 2021-05-04 21:26 UTC
Running a default Event Grid Triggered Azure function created in Visual Studio 2019 causes binding exception to be returned.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create an Event Grid Triggered Azure function using Visual Studio 2019.
2. Validate that your Microsoft.Azure.WebJobs.Extensions.EventGrid package version is v  2.1.0.
3. Run the Azure Function in the background. A command prompt will pop up.
4. Prepare a postman request formatted in Event Grid Schema. (see sample request attached)
5. Hit the url of your Azure Function e.g http://localhost:7071/admin/functions/{functionNameGoesHere}

#### Expected behavior

- Azure Function will be able to print the Event Grid message sent through Postman

#### Actual behavior

- A 202 response will be received in Postman
- An exception message will be thrown in the command prompt of the Azure Function
- See SampleException image attached
![image](https://user-images.githubusercontent.com/39720286/118293304-221c1e80-b49f-11eb-92a5-54fd852570fa.png)

#### Known workarounds

- Downgrade to v 2.0.0

#### Related information 
[SamplePostmanRequest.txt](https://github.com/Azure/azure-webjobs-sdk/files/6424038/SamplePostmanRequest.txt)

* Package version
* Links to source

**Comment by v-anvari** [comment] 2021-05-07 13:40
Hi @melvincanafranca , Thank you for reaching us. We will reproduce this issue and check if this issue is related to the latest versions, will update the findings here and triage the issue if required.

**Comment by v-anvari** [comment] 2021-05-11 11:19
@anthonychu , Do you any inputs here

**Comment by v-anvari** [comment] 2021-05-13 11:21
Hi @melvincanafranca , 

I reproduced this issue using Postman and [NGORK](https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-event-grid-trigger-local#allow-azure-to-call-your-local-function), and did not find any error.

**Results using NGORK:**
Executing 'Function1' (Reason='EventGrid trigger fired at 2021-05-13T15:19:49.6038044+05:30', Id=70b30607-56b3-4700-8dd3-2ba92687296a)

**Results using Postman:**
[2021-05-13T11:18:00.176Z] Executing 'Function1' (Reason='EventGrid trigger fired at 2021-05-13T16:48:00.1388556+05:30', Id=b82870fd-33e6-4635-82e2-42fdeadcc886)
[2021-05-13T11:18:00.185Z] {
[2021-05-13T11:18:00.187Z]   "api": "PutBlockList",
[2021-05-13T11:18:00.188Z]   "blobType": "BlockBlob"
[2021-05-13T11:18:00.188Z] }
[2021-05-13T11:18:00.212Z] Executed 'Function1' (Succeeded, Id=b82870fd-33e6-4635-82e2-42fdeadcc886, Duration=58ms)
[2021-05-13T11:18:01.467Z] Host lock lease acquired by instance ID '000000000000000000000000F38BE614'.

I have used the latest packages itself:
![image](https://user-images.githubusercontent.com/66122429/118109439-d7e36080-b3fe-11eb-8da6-0c8b10d29d0a.png)

Can you check if you have missed any header, or any other parameter after upgrading the version.

**Comment by melvincanafranca** [comment] 2021-05-13 21:35
Agree that this will work in NGROK, problem from my end is that NGROK is blocked from my enterprise's firewall which is why I'm trying to use the function's admin URL. Any suggestion on the required header for the function's URL?

**Comment by v-anvari** [comment] 2021-05-14 13:31
Hi @melvincanafranca , I used "aeg-event-type" : "Notification" and "Content-type" : "Application/json" in the postman header and it worked all fine. Let us know if that works for you

**Comment by melvincanafranca** [comment] 2021-05-14 15:28
It didn't work for me. 
![image](https://user-images.githubusercontent.com/39720286/118293146-f731ca80-b49e-11eb-94b3-9a733ac9b5c7.png)
![image](https://user-images.githubusercontent.com/39720286/118293222-0ca6f480-b49f-11eb-87ef-c93da8b91404.png)

**Comment by v-anvari** [comment] 2021-05-14 16:55
For team reference, I tried running this scenario twice with the 2 different URLs: 

1. http://localhost:7071/admin/functions/Function1 -- causes error
2. http://localhost:7071/runtime/webhooks/EventGrid?functionName=Function1 -- succeeds 
// second URL is the Default URL for triggering event grid function in the local environment.

![image](https://user-images.githubusercontent.com/66122429/118303209-d00ce480-b502-11eb-930e-9a668c34b6d0.png)

Hi @melvincanafranca , Not sure if the issue is related to the URL. Need to confirm this with the team.

**Comment by melvincanafranca** [comment] 2021-05-17 02:03
Thanks for the recommendation. The 2nd URL seems to work.

**Comment by v-anvari** [comment] 2021-05-17 09:25
Thank you for the update, closing this issue as resolved

**Closed as completed by v-anvari** 2021-05-17 09:25 UTC
