### ISSUE TITLE
BlobTrigger not detecting new files in container

### ISSUE THREAD

**Issue by rickrain** [Azure/azure-webjobs-sdk#507] opened 2015-05-06 13:48 UTC
This WebJob function signature is not getting invoked when new files are uploaded into the container. This is using v1.01 of the SDK.

`
        public static void WorkBlob([BlobTrigger("stackoverflow/{name}")] TextReader input)
        {
            Console.WriteLine(DateTime.Now);
        }
`

However, if you stop the WebJob and restart it, then it detects the new file.

See also http://stackoverflow.com/questions/30067654/azure-continuous-webjob-blob-triggering-only-once

**Comment by fsigalov** [comment] 2016-03-04 00:09
I'm seeing the same behavior with 1.1.1 and storage 6.2

**Comment by brettsam** [comment] 2016-10-24 13:35
There have been a lot of updates to the BlobListener logic since this was opened, so I'm going to close this issue. If anyone sees this, I recommend giving the latest 'nightly' release a try and see if you can reproduce this. If so, please feel free to re-open and we'll investigate.

**Closed by brettsam** 2016-10-24 13:35 UTC

**Comment by MisinformedDNA** [comment] 2016-12-16 18:57
I'm running Azure Functions locally and having the same problem. It seems to work most of the time and then gets into a "stuck" state. Restarting the project does nothing... until it magically repairs itself at some point.

**Comment by brettsam** [comment] 2016-12-16 20:00
@MisinformedDNA -- Are you using Visual Studio for your development? I wonder if the delay you're seeing is because of our Singleton lock timeout.

One way to see is to turn on verbose logs in your host.json:

``` 
{
 "tracing": {
      "consoleLevel": "verbose"
    }
}
```

Then you should see something about a Singleton lock in the messages when the host starts up.
