### ISSUE TITLE
Add support for service bus geo failover

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk#2028] opened 2018-11-20 20:16 UTC
Service Bus has a feature to enable [geo-redundant](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-geo-dr) namespaces that **creates a single connection string** that can alias across two namespaces.  At a given time you can trigger a "failover" which will route new connections to your secondary namespace.

Today in functions it appears that when a failover is initiated the host throws an exception (which I expect is expected as the namespace it established a connection with is no longer active), but it doesn't seem to recover.

Customer tried to run locally and had to manually restart the host.  Ideally we'd have some config or option so the message handler could try to reconnect, as in this scenario a reconnection with the same connection string should result in a valid connection to the secondary namespace.

**Comment by jeffhollan** [comment] 2018-11-21 17:56
I set up a failover instance in test and tested this scenario, but I was getting the below error in function after the failover. My functions was connected in debug session from my local machine and using the alias. But had to restart it to connect after the failover. 
 
 
![error](https://user-images.githubusercontent.com/7132626/48859706-ae887300-ed73-11e8-9502-8eb1ceab0523.png)


I will test the behavior of deployed azure function tomorrow.

**Comment by fabiocav** [comment] 2018-11-29 19:55
Closing this a duplicate of #2037

**Closed by fabiocav** 2018-11-29 19:55 UTC
