### ISSUE TITLE
Feature request: Run webjobs with Managed Identity of the AppService

### ISSUE THREAD

**Issue by fhurta** [Azure/azure-webjobs-sdk#2191] opened 2019-04-28 10:55 UTC
The AppService allows configuration of the Identity. When it is configured it allows web application to connect to KeyVault without storing credentials. However, webjobs running within the same AppService do not honor this configuration and connection to KeyVault fails.

Keep it consistent and use Managed Identity for webjobs as well when it is switched on on AppService

**Comment by mhoeger** [comment] 2019-05-22 20:02
@mattchenderson - mind weighing in on this feature request?

**Comment by mattchenderson** [comment] 2019-05-30 02:53
@fhurta Can you explain the issue a bit further and provide steps to reproduce? Are you dealing with triggered webjobs or continuous? Does the failure occur at the point of getting the environment variables or when making a call to the token service?

**Comment by mhoeger** [comment] 2019-06-25 17:46
Closing this issue due to lack of details, please ping if it still applies and we will reopen!

**Closed by mhoeger** 2019-06-25 17:46 UTC

**Comment by fhurta** [comment] 2019-07-01 12:08
Thanks for review, I confirm it works. Perhaps a result of my misunderstanding and the lack of information in documentation, sorry. The only docs I was able to find at that time was https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity where it was discussed in context of Functions. I asked there for info regarding to WebJobs and got negative response about MIS being supported by WebJobs, see https://github.com/MicrosoftDocs/azure-docs/issues/30235.

For those struggling to run locally from VS, check also settings in Visual Studio: Tools->Options->Azure Service Authentication->Account Selection

**Comment by mhoeger** [comment] 2019-07-01 18:41
Sorry about the trouble. @mathewc or @mattchenderson - have any ideas for a way that we can help with webjobs docs? Or maybe a doc that explains which parts of functions docs will be relevant vs. which won't for webjobs customers?
