### ISSUE TITLE
Improve error message for AppSetting resolution failure

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1156] opened 2017-05-23 20:07 UTC
Customers often add incorrect values for [AppSetting] attributed binding values. This happens often for connection/secret values. In such cases, even though we know we're trying to resolve an app setting, we don't give an error message that indicates that. In this example the bot secret value is given when an app setting is required:

```javascript
{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "myqueue",
      "connection": "my_STORAGE"
    },
    {
      "type": "bot",
      "name": "$return",
      "botId": "myBot",
      "secret": "jdiuidk984987dfkjdf.jjfdo7eijkkajdCldi88736",
      "direction": "out"
    }
  ]
}
```

This results in error message:

```
Function ($bot-reminder-function) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.bot-reminder-function'.
Microsoft.Azure.WebJobs.Host: Unable to resolve value for property 'BotAttribute.SecretSetting'.
```

For values that are attributed with [AppSetting] we should improve this to something like "Unable to resolve app setting for property 'BotAttribute.SecretSetting'. Make sure the app setting exists and has a valid value."

**Comment by lindydonna** [comment] 2017-05-23 23:32
Customers post issues to the CLI repo all the time with this error. Would love to see this fix!

**Comment by lindydonna** [comment] 2017-05-23 23:32
Btw, this is a duplicate of an issue you filed previously: https://github.com/Azure/azure-webjobs-sdk/issues/965

I would consider this a +100, given the fact that the issue was re-filed!

**Comment by mathewc** [comment] 2017-05-30 16:51
Also related to https://github.com/Azure/azure-functions-ux/issues/1403. In all cases we're misleading customers.

**Closed** 2017-06-05 22:46 UTC
Labels: in progress
