### ISSUE TITLE
Can't run Functions v2 in VS for Mac after update

### ISSUE THREAD

**Issue by likwidgames** [Azure/azure-webjobs-sdk#1905] opened 2018-09-13 16:40 UTC
Ever since I updated my packages to Microsoft.NET.Sdk.Functions 1.0.19, I can no longer test my builds in Visual Studio **Mac**. I am presented with the error below. I have tried updating my Visual Studio (stable, beta and alpha) but they don't seem to be updating the runtime version to 2.0.12x, so I'm stuck with 2.0.119, which is not supported with the latest version of the Functions Sdk.. Is there a way to manually do this?

> [2018-09-09 4:44:15 AM] Reading host configuration file '/Users/mike/Documents/Visual Studio 2017/Projects/Tests/AuthTests/bin/Debug/netstandard2.0/host.json'
[2018-09-09 4:44:15 AM] Host configuration file read:
[2018-09-09 4:44:15 AM] {}
[2018-09-09 4:44:15 AM] Starting Host (HostId=mikesmacbookpro-1782003714, InstanceId=4dad6d8c-c7b2-4876-8ce0-cef154e97eda, Version=2.0.11933.0, ProcessId=6817, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[2018-09-09 4:44:17 AM] A ScriptHost error has occurred
[2018-09-09 4:44:17 AM] System.Private.CoreLib: Could not load type 'Microsoft.Azure.WebJobs.Hosting.IWebJobsStartup' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
[2018-09-09 4:44:18 AM] Stopping Host
Function host is not running.

**Comment by paulbatum** [comment] 2018-09-15 19:51
I took the liberty of updating the post of your title since I believe this is a VS for Mac specific issue. Unfortunately it does not yet consume updates from the same feed as VS and VS Code and so it can fall further behind. 

The version number in your logs `2.0.11933.0` is out of date with our latest packages and the version that we run in Azure. You want that version number to be at least `2.0.12050` to be compatible with the latest bits. 

To confirm my theory, could you try either VS Code, or by installing and using the core tools directly (https://github.com/Azure/azure-functions-core-tools).

This sort of mismatch should not be an issue once V2 moves into general availablity, as there will be no further breaking changes at that point.

**Comment by mhoeger** [comment] 2018-10-10 16:06
@likwidgames - closing this issue. Please reopen if you continue to have problems!

**Closed by mhoeger** 2018-10-10 16:06 UTC

**Comment by likwidgames** [comment] 2018-10-10 17:04
> I took the liberty of updating the post of your title since I believe this is a VS for Mac specific issue. Unfortunately it does not yet consume updates from the same feed as VS and VS Code and so it can fall further behind.
> 
> The version number in your logs `2.0.11933.0` is out of date with our latest packages and the version that we run in Azure. You want that version number to be at least `2.0.12050` to be compatible with the latest bits.
> 
> To confirm my theory, could you try either VS Code, or by installing and using the core tools directly (https://github.com/Azure/azure-functions-core-tools).
> 
> This sort of mismatch should not be an issue once V2 moves into general availablity, as there will be no further breaking changes at that point.

VS Code uses 2.0.12050, however, Visual Studio Mac still runs at 2.0.11933.0 even with Functions V2 going to GA and all software updates. My preference is still to use Visual Studio Mac rather than VS Code, so this issue remains.

**Comment by nspillson** [comment] 2018-11-26 15:22
So what's the deal with this issue? The thread that @markosaric referenced links back to this one, and they're both indicating that Visual Studio Mac is behind in the version of Functions tooling. 

I confirmed it's the case by running from VS Code, and my functions worked as expected. Running from VS Mac they're running the 2.0.11933.0 version and failing. 

So there's an issue from 9/9, and 10/26, and not really any indication as to when this will be fixed. @mhoeger, @markosaric, can you give some guidance on when this will be resolved?

**Comment by nspillson** [comment] 2018-11-27 21:30
Thanks for the update. With a couple of plugins the VS Code experience is pretty solid for Function development.
