### ISSUE TITLE
ServiceBusTrigger won't handle messages with null body

### ISSUE THREAD

**Issue by HolopaMir** [Azure/azure-webjobs-sdk#1677] opened 2018-04-25 09:48 UTC
#### Repro steps

1. Send servicebus message with null body
2. Retrieve it with v2 functions with ServiceBus extension library

#### Expected behavior

[ServiceBusTrigger("")] should get the actual message from the servicebus and still run so you can still access message metadata (eg. Message label, UserProperties), even tough your message has no body (or body is null)

#### Actual behavior

When message body is null, function runtime throws exception: Exception binding parameter 'messageItem'. Ends in: Microsoft.Azure.WebJobs.ServiceBus: Object reference not set to an instance of an object.

#### Known workarounds

Add anything to message's body, if it is going to be null.

#### Related information 

Body could be null with the old and removed BrokeredMessage and v1 function trigger could still manage to handle the message.

Packages used:
* Microsoft.Azure.WebJobs.ServiceBus 3.0.0-beta5
* Microsoft.NET.Sdk.Functions 1.0.13

**Comment by paulbatum** [comment] 2018-04-25 17:32
Dupe of #1644.  There is a fix in PR:
https://github.com/Azure/azure-webjobs-sdk/pull/1670

**Closed by paulbatum** 2018-04-25 17:32 UTC
