### ISSUE TITLE
Publishing a V2 Functions App in Visual Studio creates an app that is unable to start

### ISSUE THREAD

**Issue by bzhu94** [Azure/azure-webjobs-sdk#1669] opened 2018-04-18 17:43 UTC
### Repro steps

1. In Visual Studio, create a v2 Functions project with the HttpTrigger template

2. Add a BlobTrigger function to the project.

3. Publish the project to a new Function App in Azure from Visual Studio. Make sure to click OK/Yes to any dialogs that pop up.

#### Expected behavior

A running Function App should be created.

#### Actual behavior

The Function App created contains all the proper Functions, but the app fails to start and gives the following error when I click into a Function on Azure:

![image](https://user-images.githubusercontent.com/8541576/38948475-9830e5ee-42f4-11e8-9ce8-4c709a35ac87.png)

When I go to the app site URL (myfunction.azurewebsites.net), I get an Http Error 502.5.
 
#### Known workarounds

None that I know of

#### Related information 

This is using the VS tooling for Functions with templates from:

o	Item templates: https://www.myget.org/F/azure-appservice/api/v2/package/Azure.Functions.Templates/2.0.0-beta-10177
o	Project templates: https://www.myget.org/F/azure-appservice/api/v2/package/Microsoft.AzureFunctions.ProjectTemplates/2.0.0-beta-10177

This issue does not consistently repro.

**Comment by paulbatum** [comment] 2018-04-18 17:54
@bzhu94 I assume this does not repro for you with the current prod bits? I just ran through it myself and had no problems...

**Comment by paulbatum** [comment] 2018-04-18 18:02
@soninaren I know the current feed points at 10177.. did we have a test pass with this version?

**Comment by paulbatum** [comment] 2018-04-18 20:54
@bzhu94 I chatted with Naren, he showed me how to find what version my current VS is using:

```
λ dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs\Templates\2.0.0"


    Directory: C:\Program Files (x86)\Microsoft Visual
    Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs\Templates\2.0.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         4/6/2018   9:41 AM          38757 Azure.Functions.Templates.2.0.0-beta-10177.nupkg
-a----         4/6/2018   9:41 AM           5954 Microsoft.AzureFunctions.ProjectTemplates.2.0.0-beta-10177.nupkg
```

So it looks like i'm using the same bits as you and I can't reproduce.

**Comment by soninaren** [comment] 2018-04-25 20:17
this is a no repro for @bzhu94 as well. Closing this one for now. Please re-open if you hit this again.

**Closed by soninaren** 2018-04-25 20:17 UTC
