### ISSUE TITLE
keep getting Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less

### ISSUE THREAD

**Issue by YangLi01** [Azure/azure-webjobs-sdk#675] opened 2016-03-25 21:39 UTC
if I have multiple jobs running at the same time and using log.writeline to write log every a few seconds, I get the following error occasionally. This causes our jobs fail sometime and we can't catch this error to report the issue. it looks like StringBuilder in UpdateOutputLogCommand.UpdateOutputBlob has concurrency issue.

Error:
[03/25/2016 14:22:29 > bdae78: ERR ] 
[03/25/2016 14:22:29 > bdae78: ERR ] Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
[03/25/2016 14:22:29 > bdae78: ERR ] Parameter name: chunkLength
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Text.StringBuilder.ToString()
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.IO.StringWriter.ToString()
[03/25/2016 14:22:29 > bdae78: ERR ]    at Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand.<UpdateOutputBlob>d__10.MoveNext()
[03/25/2016 14:22:29 > bdae78: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[03/25/2016 14:22:29 > bdae78: ERR ]    at Microsoft.Azure.WebJobs.Host.Loggers.UpdateOutputLogCommand.<TryExecuteAsync>d__3.MoveNext()
[03/25/2016 14:22:29 > bdae78: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/25/2016 14:22:29 > bdae78: ERR ]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[03/25/2016 14:22:30 > bdae78: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.RecurrentTaskSeriesCommand.<ExecuteAsync>d__0.MoveNext()
[03/25/2016 14:22:30 > bdae78: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[03/25/2016 14:22:30 > bdae78: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.<RunAsync>d__d.MoveNext()
[03/25/2016 14:22:30 > bdae78: ERR ] --- End of stack trace from previous location where exception was thrown ---
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[03/25/2016 14:22:30 > bdae78: ERR ]    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.<>c__DisplayClass1.<Throw>b__0()
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[03/25/2016 14:22:30 > bdae78: ERR ]    at System.Threading.ThreadHelper.ThreadStart()
[03/25/2016 14:22:30 > bdae78: SYS ERR ] Job failed due to exit code -532462766
[03/25/2016 14:22:30 > bdae78: SYS INFO] Process went down, waiting for 0 seconds

**Comment by steinmr** [comment] 2016-04-01 08:29
I also get this error quite frequently, but only when I run trigger events in parallell using the BatchSize property.

Could you explain a bit how your application works?

I use unity to do DI, but I do not think that is the cause, because I refactored quite a bit to make sure the TextWriter that is passed to the QueueTrigger method is not reused between threads.

What I do:
I use JobHostConfiguration to specify a custom unity container where I define some dependencies that are common (and thread safe) for all invoctions of QueueTrigger.
I then create a new container in every QueueTrigger invocation as a child container of the container above, that creates all dependencies that can not be shared between threads. Included in this is a class that wraps the TextWriter sent into the QueueTrigger.

In my mind, this should ensure that the TextWriter is never acessed cross thread, unless the SDK itself re-uses it between invocations. Or this error is caused by something else.

As a side note: It would be very helpful if the SDK contained some more details on where threading in done, so we can avoid threading issues in our own code. (Like is the class that contains the QueueTrigger method created once or for every invocation.

**Comment by YangLi01** [comment] 2016-04-01 19:44
I set BatchSize=7 and NewBatchThreshold = 6. If you use TextWriter to print out log very often and you have multiple jobs running at the same time, you will get the error. For my case, I have 7 jobs running at the same time and I print out log around every 2 seconds.
I am thinking if StringBuilder is not thread safe, UpdateOutputLogCommand.UpdateOutputBlob may have issue.
 
        private async Task UpdateOutputBlob(CancellationToken cancellationToken, bool flushAndClose = false)
        {
            ThrowIfDisposed();

            string snapshot;
            lock (_writerSyncLock)
            {
                if (flushAndClose)
                {
                    _synchronizedWriter.Flush();
                }

                snapshot = _innerWriter.ToString();

                if (flushAndClose)
                {
                    _synchronizedWriter.Close();
                    _innerWriter.Close();
                }
            }

            // when we write the output blob, ensure that we always include
            // any preexisting contents
            string existingText = await GetExistingContent(cancellationToken);
**##             StringBuilder sb = new StringBuilder(existingText); //why this code is not in the lock?**
            sb.Append(snapshot);
            snapshot = sb.ToString();

            await _uploadCommand.Invoke(snapshot, cancellationToken);
        }

**Comment by mathewc** [comment] 2016-04-05 04:04
Thanks for reporting guys. We'll look into it.

**Comment by steinmr** [comment] 2016-04-05 12:06
Just as an update, I rewrote my application to use async/await throughout (including for the QeueueTrigger method), and it has not happened yet after that deployment. But I have to wait until tonight to get enough load to know for sure it it fixed the problem. Will report back.
But even if it did fix it, I guess that synchronous code should also be supported by the API?

**Comment by mathewc** [comment] 2016-09-27 15:51
@brettsam Can you take a look at this one? I think we may have a threading issue in the TextWriter.

**Comment by brettsam** [comment] 2016-09-27 17:29
It looks like the issue is with this line: https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Loggers/UpdateOutputLogCommand.cs#L142.

While all writes to the `StringWriter` are thread-safe (we're using `TextWriter.Synchronized`), the call to `ToString()` isn't. So if you're writing from another thread while `ToString()` is doing its thing internally, you can get this exception.

Trying to figure out the best fix for this.

**Closed** 2016-09-27 22:39 UTC
Labels: in progress

**Comment by Schenz** [comment] 2016-11-14 20:53
It appears that nothing has been deployed to NuGet since April.  Do I have to wait til the 2.0.0 release (or build it myself) to get this bug fix for my projects?

**Comment by brettsam** [comment] 2016-11-14 20:54
You can grab a 'nightly' build -- https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds. The newest ones will have this fix.

**Comment by Schenz** [comment] 2016-11-14 20:55
I'm a bit leary of doing this for a production deployed solution....

**Comment by mathewc** [comment] 2016-11-14 22:04
I'm about to push our beta2 bits to nuget.org in the next day.

**Comment by zizhenms** [comment] 2018-01-25 21:42
I am using the latest 2.0.0.0 version but the issue still repros for me

**Comment by brettsam** [comment] 2018-01-25 21:51
@zizhenms -- Can you share the stack trace?
