### ISSUE TITLE
Exception when AzureWebJobsDashboard is removed

### ISSUE THREAD

**Issue by fwd079** [Azure/azure-webjobs-sdk#629] opened 2016-02-12 16:42 UTC
Hello,
Continued from [this StackOverflow question](http://stackoverflow.com/q/35345928/1659999) . If we do not want logging functionality then if we remove **AzureWebJobsDashboard** from connectionStrings then we get InvalidOperationException, telling us the ways how to add `DashboardConnectionString` properly.

Currently only solution is to pass null inside code. Something like:

`config.DashboardConnectionString = null;`

Easily testable by creating an Azure WebJob and then removing the AzureWebJobsDashboard from connectionStrings section of app.config file.

Thanks.

**Comment by christopheranderson** [comment] 2016-04-12 20:14
May be fixed. @mathewc to verify

**Comment by paulbatum** [comment] 2016-05-16 22:27
Dupe of #379

**Closed by paulbatum** 2016-05-16 22:27 UTC
Labels: Feature

**Comment by fwd079** [comment] 2016-05-17 15:05
Urrm, the bug is changed from "feature" to a "backlog"? Seriously?

**Comment by mathewc** [comment] 2016-05-17 16:25
Also related to https://github.com/Azure/azure-webjobs-sdk/issues/563

**Comment by fwd079** [comment] 2016-05-18 06:07
@mathewc cheers mate. :)
