### ISSUE TITLE
AzureWebJobsDashboard not working with ZRS storage

### ISSUE THREAD

**Issue by baywet** [Azure/azure-webjobs-sdk#1067] opened 2017-03-16 19:01 UTC
#### Repro steps

1. Create a ZRS, Resource Manager, General Purpose storage

1. Use the connection string as input parameter of the JobHostConfiguration

2. Receive a message (Service Bus in my case but I don't think it matters)

#### Expected behavior

Webjob logging entries to the dashboard

#### Actual behavior

Getting an exception: `Unhandled Exception: System.InvalidOperationException: Storage account 'accountname' is of unsupported type 'BlobOnly'. Supported types are 'GeneralPurpose'`
Web job when published to an Azure app service, keeps restarting.

#### Known workarounds

Creating and using a GRS instead.

#### Related information 
WebJob SDK 2.0.0.0, .NET "classic" 4.5.2

**Comment by christopheranderson** [comment] 2017-03-27 17:20
@mamaso - can you confirm this repros for all ZRS accounts?

**Comment by mamaso** [comment] 2017-03-28 05:09
Looks like this is all ZRS, see [here](https://blogs.msdn.microsoft.com/windowsazurestorage/2014/08/01/introducing-zone-redundant-storage/)

> Since ZRS accounts do not support page blob, file, table or queue, any attempt to create or manipulate those objects on a ZRS storage account will fail.

**Comment by mamaso** [comment] 2017-03-28 05:45
Closing this as by design.

Related to https://github.com/Azure/azure-webjobs-sdk/issues/810

Just one more piece of info, these ZRS accounts are usable, but not as primary storage accounts - i.e. `AzureWebJobsDashboard` or `AzureWebJobsStorage`.  You can create another app setting `MyZRSStorageAccount` and create a function something like this:

```
public static void BlobToBlob_DifferentAccounts_SecondaryToPrimary(
            [BlobTrigger(Input + "/{name}"), StorageAccount("MyZRSStorageAccount")] string input,
            [Blob(Output + "/{name}")] out string output)
        {
            output = input;
        }
```

**Comment by baywet** [comment] 2017-03-28 12:44
Thanks for investigating. Maybe the error should be more explicit though and documentation should include the fact that ZRS is not supported? It took quite some time to figure out what was the issue on a production workload, and it used to be working fine before we updated the SDK. Having proper error and doc would have helped a lot.

**Comment by mamaso** [comment] 2017-03-28 16:56
Yep, the error could be improved to indicate that it could be a blob-only or ZRS account.  We unfortunately have no way to discover exactly what type of account you have from the connection string.

I can update the docs to indicate that ZRS accounts are not supported as well

**Comment by mamaso** [comment] 2017-04-20 17:13
Closing this thanks to #1101 - we won't be able to support ZRS, but we now have better warnings for it

**Closed by mamaso** 2017-04-20 17:13 UTC
Labels: bug

**Comment by zhangruiskyline** [comment] 2017-10-28 04:22
Hi, I am getting the same error, dose that mean my Azure blob account dose not support Azure functions? Or anything I need to change?

**Comment by baywet** [comment] 2017-10-28 13:02
Blob zrs accounts are not supported, I had to re-create my storage account to fix the issue

**Comment by zhangruiskyline** [comment] 2017-10-28 20:54
I checked my Azure blob should be Locally-redundant storage (LRS), not ZRS, it should work for this web job work, right?

**Comment by baywet** [comment] 2017-10-28 21:54
There are two important settings as far as I can remember the replication as well as the type of storage.

**Comment by zhangruiskyline** [comment] 2017-10-29 03:40
So which type of storage is supported for web job?

**Comment by baywet** [comment] 2017-10-30 12:03
In my case general purpose GRS account on resource manager model with a standard performance level works fine

**Comment by solidcloudio** [comment] 2018-08-08 06:53
This seems to have regressed.  It doesnt seem to work with General Purpose v1 or General Purpose v2 bot LRS

`System.InvalidOperationException: Storage account 'bitstrader2' is of unsupported type 'Blob-Only/ZRS'. Supported types are 'General Purpose'
[08/08/2018 06:50:01 > bc2a75: ERR ]    at Microsoft.Azure.WebJobs.Host.Storage.StorageAccountExtensions.AssertTypeOneOf(IStorageAccount account, StorageAccountType[] types)
[08/08/2018 06:50:01 > bc2a75: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<CreateAndValidateAccountAsync>d__24.MoveNext()
[08/08/2018 06:50:01 > bc2a75: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/08/2018 06:50:01 > bc2a75: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/08/2018 06:50:01 > bc2a75: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/08/2018 06:50:01 > bc2a75: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<TryGetAccountAsync>d__25.MoveNext()
[08/08/2018 06:50:01 > bc2a75: ERR ] --- End of stack trace from previous location where exception was thrown ---`

**Comment by paulbatum** [comment] 2018-08-08 23:04
The error message says the following - `Storage account 'biasdfaader2' is of unsupported type 'Blob-Only/ZRS'` - are you saying that the code is incorrectly detecting the type of this account? What is the type of this account, and what version of webjobs/functions are you using?

**Comment by solidcloudio** [comment] 2018-08-08 23:12
I've tried to create 3 different types of Azure Storage accounts, for use in AzureWebJobsDashboard or AzureWebJobsStorage.   New storage accounts offer LRS, GRS & RA-GRS.  So I created 3 storage accounts, one of each type.  I get this ZRS error regardless of which storage account I try to use..


Interestingly, When running locally.. the JobHost.RunAndBlock() works, but I get an IP:443 timeout about 2 minutes later.    When running in an Azure hosted Webjob, I see the ZRS error.


Development storage locally appears to work.  But I'm still confused as to the type of storage account I need to get a WebJob to run?  That seems to be the question.  I didn't see any constraints or requirements that said I need a certain type of storage account?

**Comment by paulbatum** [comment] 2018-08-08 23:51
Most users just use a general purpose V1 account (shouldn't matter whether you pick LRS or GRS). If this was regressed, we would have many many users complaining so I think it must be an issue with your app or config.

Perhaps you're using outdated bits? You should be referencing webjobs 2.2.0.

**Comment by MrCsabaToth** [comment] 2018-08-25 22:52
I'm battling with this as well
