### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2 depends on Microsoft.Azure.WebJobs (>= 3.0.17) but Microsoft.Azure.WebJobs 3.0.17 was not found. An approximate best match of Microsoft.Azure.WebJobs 3.0.18 was resolved.

### ISSUE THREAD

**Issue by YvonneArnoldus** [Azure/azure-webjobs-sdk#2678] opened 2021-03-01 08:07 UTC
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Use Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.0 in a Project
2. Upgrade the package to Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2

#### Expected behavior

Upgrade the packages to Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2

#### Actual behavior

Get the error:

Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2 depends on Microsoft.Azure.WebJobs (>= 3.0.17) but Microsoft.Azure.WebJobs 3.0.17 was not found. An approximate best match of Microsoft.Azure.WebJobs 3.0.18 was resolved.
Package restore failed. Rolling back package changes for 'Project.Name'.

**Comment by v-anvari** [comment] 2021-03-01 12:23
Hi @YvonneArnoldus , The error is because the package Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2 is dependent on any version greater than 3.0.17. Can you tell us the Webjobs version that you are using. 

![image](https://user-images.githubusercontent.com/66122429/109496557-d1f40980-7ab6-11eb-9eb2-9dffc0c47933.png)

**Comment by YvonneArnoldus** [comment] 2021-03-01 14:25
Hi,

I have no reference to any Microsoft.Azure.WebJobs but I do have a reference to Microsoft.Azure.WebJobs.Extensions.Storage 4.0.4 which has dependencies

.NETStandard 2.0
Microsoft.Azure.Cosmos.Table (>= 1.0.7)
Microsoft.Azure.Storage.Blob (>= 11.1.7)
Microsoft.Azure.Storage.Queue (>= 11.1.7)
Microsoft.Azure.WebJobs (>= 3.0.22)

And this packages works fine without errors. So it is not my Microsoft.Azure.WebJobs version.

But if you check https://www.nuget.org/packages/Microsoft.Azure.WebJobs/

Then you will see there isn't any 3.0.17 version of Microsoft.Azure.Webjobs so that might be the issue,

**Comment by v-anvari** [comment] 2021-03-01 16:50
Hi @YvonneArnoldus, yes you are right, it works with versions greater than 3.0.17. This package must have been removed, though it looks like the package shall be updated. I will update this internally to get it updated. 

Thankyou

**Comment by v-anvari** [comment] 2021-03-01 17:46
Reproduced the issue and the Error is just a warning, not a blocker. This is resolved by VS by downloading the latest version. Require an upgrade to 3.0.18 to suppress the warning and not to search for 3.0.17

Warning : Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2 depends on Microsoft.Azure.WebJobs (>= 3.0.17) but Microsoft.Azure.WebJobs 3.0.17 was not found. An approximate best match of Microsoft.Azure.WebJobs 3.0.18 was resolved.	

![image](https://user-images.githubusercontent.com/66122429/109536774-2497ea80-7ae4-11eb-8683-152c9176ead1.png)

**Comment by KenBrannigan** [comment] 2021-04-17 00:53
I have the same issue and my functions app is referencing Microsoft.NET.Sdk.Functions v3.0.11 which has a reference to Microsoft.Azure.WebJobs v3.0.23. I had to downgrade to Microsoft.Azure.WebJobs.Extensions.SendGrid v3.0.0 for the warning to go away.

**Comment by v-anvari** [comment] 2021-11-01 10:50
Closing this issue as this has been fixed

**Closed as completed by v-anvari** 2021-11-01 10:50 UTC

**Comment by YvonneArnoldus** [comment] 2022-09-13 09:55
> Reproduced the issue and the Error is just a warning, not a blocker. This is resolved by VS by downloading the latest version. Require an upgrade to 3.0.18 to suppress the warning and not to search for 3.0.17
> 
> Warning : Severity Code Description Project File Line Suppression State Warning NU1603 Microsoft.Azure.WebJobs.Extensions.SendGrid 3.0.2 depends on Microsoft.Azure.WebJobs (>= 3.0.17) but Microsoft.Azure.WebJobs 3.0.17 was not found. An approximate best match of Microsoft.Azure.WebJobs 3.0.18 was resolved.
> 
> ![image](https://user-images.githubusercontent.com/66122429/109536774-2497ea80-7ae4-11eb-8683-152c9176ead1.png)

I'm using the latest version of VS 2022 and it still listed as a warning. 

I know it is not breaking, but I like my code without Errors, Warnings and Message, because in some cases you need to solve warnings in order to make your code work and it doesn't help if you have Warnings that can't be solved.

Which is impossible while using this package, because it references a non existing version of a package.
