### ISSUE TITLE
Function execution log gets overwritten with exception string from handling output parameter 

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-webjobs-sdk#969] opened 2017-01-11 20:58 UTC
Please provide a succinct description of the issue.
If function fails to write to output binding, only the binding error is visible in logs. Previous function execution logs get overwritten. 

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A Create a function with TraceWriter and Bind to an ICollector . 
2. Step B log to the TraceWriter and present some malformed data to the ICollector.  
3. Step B execute the function

#### Expected behavior

Previously emitted logs in the execution should be maintained. Note in this case, I dont know if the input was bad. or if it was some flakiness in writing the output data.

#### Actual behavior

Only the binding  exception is present. 

```
Error while handling parameter sendEmailBatch after function returned:
...Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Tables.TableEntityWriter`1.<FlushPartitionAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Tables.TableEntityWriter`1.<FlushAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
      --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
      --- End of inner exception stack trace ---
```

#### Known workarounds

None
#### Related information 

Provide any related information 

* Package version 
* Links to source Here is a sample:
```javascript
public static async Task<object> Run(HttpRequestMessage req, ICollector<SendEmailBatch> sendEmailBatch, TraceWriter log)
{
    log.Info($"C# HTTP trigger function processed a request. RequestUri={req.RequestUri}");
....     
     /// If this throws an error when handling after the previous execution completes, the previous log is not captured by the sdk
sendEmailBatch.Add(input);

 return "";
 

}
```

**Comment by fashaikh** [comment] 2017-01-27 00:24
Ping ! any thoughts on this ?

**Comment by christopheranderson** [comment] 2017-01-27 00:48
@paulbatum - please assign for investigation

**Comment by mathewc** [comment] 2017-01-27 04:14
Thanks for the detailed repro steps @fashaikh. We'll find someone to look at this ASAP. Is this just using the SDK, or in the context of Azure Functions? @mamaso @brettsam any ideas?

**Comment by mamaso** [comment] 2017-01-30 22:52
Also, @fashaikh is this a one time issue or something you can easily repro? And interested in the functions / webjobs context as well.

Doing some thinking about how to trigger an ICollector failure, maybe I could intercept the underlying request with fiddler and fail it, or use a MessageSenderCollector with an IConverter that throws.

Couldn't repro by throwing an error outside of the ICollector at least.

**Comment by fashaikh** [comment] 2017-01-30 22:57
I have seen it happen quite a few times. 
I think it happens if the payload to the `ICollector` is fairly large . I haven't seen it since I started truncating the input going input going into the `ICollector`

**Comment by mamaso** [comment] 2017-03-27 16:54
Couldn't reproduce this using a `TraceWriter` and a `ICollector` hooked up to a queue in functions or webjobs, it's possible that @fabiocav 's error improvements helped here.

**Comment by paulbatum** [comment] 2017-03-27 16:57
Closing as no repro. @fashaikh please reopen if you see this again.

**Closed by paulbatum** 2017-03-27 16:57 UTC
Labels: bug
