### ISSUE TITLE
Link to the cheat sheet/quick binding pdf is broken

### ISSUE THREAD

**Issue by alexsorokoletov** [Azure/azure-webjobs-sdk#1260] opened 2017-07-27 04:59 UTC
This issue is regarding wiki documentation in the repo.

PDF is mentioned here https://github.com/Azure/azure-webjobs-sdk/wiki as "Quick Reference Bindings PDF" and also here https://github.com/Azure/azure-webjobs-sdk/wiki/Trigger-Binding-Data as "The Azure WebJobs Cheat Sheet".

Both links are broken.

I was able to find a copy of the pdf here https://jhaleyfiles2016.blob.core.windows.net/public/Azure%20WebJobs%20SDK%20Cheat%20Sheet%202014.pdf but this is definitely not an official source.

Thank you.

**Comment by AZDeveloper777** [comment] 2017-09-18 23:32
The link in the Wiki page still appears to be broken. Why was this issue closed ?

**Comment by paulbatum** [comment] 2017-09-18 23:44
This issue isn't closed. The linked bug was closed because its a dupe of this one.

(I don't have any context on why the download link is still busted, sorry)

**Comment by christopheranderson** [comment] 2017-11-01 18:47
@tdykstra could you please look at this?

**Comment by tdykstra** [comment] 2017-11-17 03:49
@christopheranderson Sorry for late response -- for some reason I didn't get an email from your "look at this" comment.  I've restarted the email thread about this from a year ago.  Last I heard, Monica was looking into it.

**Comment by ggirard07** [comment] 2018-02-19 19:34
Still not working as of today

**Comment by tdykstra** [comment] 2018-02-20 18:00
I checked on the status of this and the latest plan is to host it in GitHub.  I'll post back here when I hear more.  Apologies for how long this has taken.

**Comment by tdykstra** [comment] 2018-03-06 23:59
The wiki page that still has a link to the Quick Reference has been updated:
https://github.com/Azure/azure-webjobs-sdk/wiki/Trigger-Binding-Data

The file is now a .png rather than a .pdf and is available at this url:
https://docs.microsoft.com/azure/app-service/media/web-sites-create-web-jobs/webjobs-sdk-quick-reference.png

**Closed by tdykstra** 2018-03-06 23:59 UTC
