### ISSUE TITLE
New logging: function invocation log is broken

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk#669] opened 2016-03-21 19:32 UTC
Function list shows correct calls, e.g.

![image](https://cloud.githubusercontent.com/assets/556238/13931501/e03030aa-ef60-11e5-8077-7edcb1d79a9d.png)

But clicking on one shows:

![image](https://cloud.githubusercontent.com/assets/556238/13931525/f5a7c7ea-ef60-11e5-8261-bee09a6a894e.png)

**Comment by MikeStall** [comment] 2016-03-23 03:33
I think the problem is that it's not getting flushed. Logs are batched, and there should be a background poller that flushes these.

**Comment by MikeStall** [comment] 2016-03-23 21:36
Fixed by pulling latest Logging SDK into Scripts.

**Closed by MikeStall** 2016-03-23 21:36 UTC
