### ISSUE TITLE
Table binding to IQueryable<TElement> breaks on WindowsAzure.Storage SDK 8+

### ISSUE THREAD

**Issue by FrankHoogmans** [Azure/azure-webjobs-sdk#1397] opened 2017-10-23 08:20 UTC
Please provide a succinct description of the issue.
Table binding throws the following exception when the WindowsAzure.Storage package is on v8 or higher.
 A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1.Run'. Microsoft.Azure.WebJobs.Host: GenericArguments[0], 'FunctionApp1.Function1+Person', on 'Microsoft.Azure.WebJobs.Host.Tables.TableExtension+TableToIQueryableConverter`1[TElement]' violates the constraint of type 'TElement'. mscorlib: GenericArguments[0], 'FunctionApp1.Function1+Person', on 'Microsoft.Azure.WebJobs.Host.Tables.TableExtension+TableToIQueryableConverter`1[TElement]' violates the constraint of type parameter 'TElement'.

The TElement is of type Person which inherits TableEntity, and this works as expected on WindowsAzure.Storage v7.2.1. As per the documentation on: 
https://github.com/Azure/azure-webjobs-sdk/wiki/Tables#-how-to-read-multiple-entities-from-a-table

Issue found when using Microsoft.Azure.WebJobs.Extensions.DurableTask which internally depends on DurableTask.AzureStorage (>= 1.0.0-beta), which depends on WindowsAzure.Storage WindowsAzure.Storage (>= 8.3.0), which conforms to the requirements set by this package (WindowsAzure.Storage (>= 7.2.1)).

#### Repro steps
Run function app in https://github.com/FrankHoogmans/AzureFunctions-TableBinding-issue

#### Expected behavior
Table binding works like with WindowsAzure.Storage 7.2.1

#### Actual behavior
Exception that the Person class does not implement ITableEntity

#### Known workarounds
None

#### Related information 
* Package versions
Microsoft.Azure.WebJobs (= 2.1.0-beta4)
Microsoft.NET.Sdk.Functions 1.0.6 (specifically depending on Microsoft.Azure.WebJobs (= 2.1.0-beta4))
WindowsAzure.Storage 8.5.0

* Links to source
https://github.com/FrankHoogmans/AzureFunctions-TableBinding-issue

**Comment by paulbatum** [comment] 2017-10-23 19:38
It is expected behavior that you need to use storage 7.x when running on functions 1.x. However it is a bug that this version of durable functions depends on storage 8.x. I have filed that bug [here](https://github.com/Azure/azure-functions-durable-extension/issues/78).

Closing this issue as its not a functions bug per se. Please follow up on the durable functions bug I linked if you need to discuss this further.

**Closed by paulbatum** 2017-10-23 19:38 UTC

**Comment by apmorton** [comment] 2017-11-02 08:16
what is the issue with updating the storage dependency on webjobs to 8.x?
Is this something that just hasn't been done because it hasn't been an issue, or is there some blocking issue that is preventing it?

This is the the second time _today_ I have encountered the issue of webjobs depending on 7.2.1 effectively breaking officially documented use cases of webjobs inside azure functions.

As it stands, the dependency on 7.2.1 prevents durable functions from working _and_ prevents the queue api's from populating the messageId and popReceipt fields when adding a queue entry.
