### ISSUE TITLE
Exception in client function causes function host to restart.

### ISSUE THREAD

**Issue by sadgit** [Azure/azure-webjobs-sdk#2085] opened 2019-01-16 10:37 UTC
As a Function Developer
In order to monitor failures
I need to exit a function with different exit codes 
and to control whether a failing message is retried or dead-lettered

##### Temporary Failure
```
Given V.2 Service Bus Trigger
When the client function throws an temporary execution error
Then the message should be retried
```
##### Permanent Failure
```
Given V.2 Service Bus Trigger
When the client function throws an permanent execution error
Then the message should be dead-lettered
```
#### Actual behavior
```
Given V.2 Service Bus Trigger
When the client function throws any exception
Then the function host is restarted
And the telemetry is not sent to AppInsights
```
#### Known workarounds

No known workarounds.

**Comment by fabiocav** [comment] 2019-01-23 20:00
Closing this as a duplicate of https://github.com/Azure/azure-webjobs-sdk/issues/2087 as the information there covers this as well.

**Closed by fabiocav** 2019-01-23 20:00 UTC

**Comment by sadgit** [comment] 2019-01-23 21:11
@fabiocav - This is a different condition.

This ticket relates to the restart behaviour, not the specific use case of a Permanent (Dead-Letter) failure

**Comment by StingyJack** [comment] 2019-03-11 06:50
@fabiocav - please reopen this. We need to know how to report failure for a webjob (2.x preferably) invocation and not have it terminate the process. This process termination stops AppInsights from being able to capture the snapshot for debugging.

**Comment by sadgit** [comment] 2019-03-11 11:24
@fabiocav - Please re-open. as @StingyJack states.
It is important to be able to report different outcomes to AppInsights and the lack of a try-catch block around the client function prevents accurate diagnosis of any failure conditions.
On the face of it - it seems to be the simplest fix of ensuring that any exceptions are handled and there should be no condition that restarts the entire function host.

**Comment by sadgit** [comment] 2019-03-11 12:00
@fabiocav @mathewc - Also please re-open both #2085 #2086 #2087 as your unwillingness to improve the product reflects extremely badly on the dependability AzureFunctions as a platform.

**Comment by fabiocav** [comment] 2019-03-13 22:59
>  as your unwillingness to improve the product

I'm sorry if you're getting this impression, but that is absolutely not the case. We have looked at your reports and followed up on them; we do need your help with repros where requested as we're unable to validate the behavior you're reporting. Can you please provide some help with that?
