### ISSUE TITLE
DecoderFallbackException trying to bind to string message with ServiceBusTrigger

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-webjobs-sdk#550] opened 2015-07-28 13:49 UTC
I am experiencing an exception when triggering a job using the ServiceBusTrigger. My job method has the following signature:

`public void Handle([ServiceBusTrigger(Topic, Subscription)] string formEntryId)`

The code that puts the message on the service bus sets the ContentType property as text/plain:

    // formEntry.Id is a string such as "FormEntry-232"
    var message = new BrokeredMessage(formEntry.Id);
    message.ContentType = "text/plain";
    topicClient.Send(message);

According to everything I've read, and looking at the source code for [BrokeredMessageToStringConverter.cs](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/BrokeredMessageToStringConverter.cs) this should work without issue.

Unfortunately my web job is producing the following exception:

	Exception while executing:
	System.InvalidOperationException: Exception binding parameter 'formEntryId' ---> System.Text.DecoderFallbackException: Unable to translate bytes [99] at index 61 from specified code page to Unicode.
	   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
	   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
	   at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBytes, Char*& chars)
	   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
	   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)
	   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
	   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
	   at System.IO.StreamReader.<ReadBufferAsync>d__28.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__19.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.Azure.WebJobs.ServiceBus.Triggers.ConverterArgumentBindingProvider`1.ConverterArgumentBinding.<BindAsync>d__0.MoveNext()

Oddly, when I view the message in Service Bus Explorer and re-submit it from the dead letter queue, the message is processed correctly.

Binding to BrokeredMessage and doing a `message.GetBody<string>()` works fine as well.

**Comment by rustd** [comment] 2015-07-29 00:22
If you need to send a string then you need to set the Stream. The following sample shows how to send the message and receive it. https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/ServiceBus/Program.cs#L42
```C#
            using (Stream stream = new MemoryStream())
            using (TextWriter writer = new StreamWriter(stream))
            {
                writer.Write(formEntry.Id);
                writer.Flush();
                stream.Position = 0;
                topicClient.Send(new BrokeredMessage(stream) { ContentType = "text/plain" });
            }
```

**Comment by rustd** [comment] 2015-07-29 17:37
Closing as this is not a bug.

**Closed by rustd** 2015-07-29 17:37 UTC
