### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions 3.0.5 depends on Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11)

### ISSUE THREAD

**Issue by SurushS** [Azure/azure-webjobs-sdk#2386] opened 2019-12-13 10:53 UTC
I seem to be getting a warning that a package is not found on nuget, which also seems to be the case.

The exact error is:

**warning NU1603: Microsoft.Azure.WebJobs.Extensions 3.0.5 depends on Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11) but Microsoft.Azure.WebJobs.Host.Storage 3.0.11 was not found. An approximate best match of Microsoft.Azure.WebJobs.Host.Storage 3.0.13 was resolved.**

Whenever i'm using azure functions sdk  with version 1.0.3x which depends on the webjobs sdk, i keep getting this warning. If i backtrack on nuget.org, i see that indeed the Azure functions sdk depends on
**Microsoft.Azure.WebJobs.Extensions 3.0.5** and that that one in turn depends on **Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11)**. However 3.0.11 does not exist. there seems to be a gap between **Microsoft.Azure.WebJobs.Host.Storage 3.0.8** and **Microsoft.Azure.WebJobs.Host.Storage 3.0.13** so it resolves the 3.0.13 version. Is this an issue? i assume it's all backwards compatible since its a patch version but i just want to check why there is a dependency to a version that does not exist?

``` xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
 <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.3x" />
  </ItemGroup>
```

**Comment by Agendum** [comment] 2019-12-16 19:31
I can easily reproduce this with a brand new project, following: https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started

**Comment by DarinMacRae** [comment] 2019-12-31 19:05
I am seeing this as well after updating from 1.0.29 to 1.0.31. It doesn't make sense why it would complain at all since 3.0.13 *IS* >= 3.0.11.

**Comment by AtOMiCNebula** [comment] 2020-01-03 20:36
It is >= 3.0.11, but NuGet picks the lowest version it can based on criteria instead of then newest.  You really don't want your build to pass one day and fail the next just because some new sub-dependency was released and you haven't had a chance to validate.  This is just NuGet letting you know that something is amiss.

I added an explicit reference to v3.0.14 to work around this (which was needed, since my CI pipeline treats warnings as errors, so this was blocking).

**Comment by AtOMiCNebula** [comment] 2020-01-03 20:38
FYI @fabiocav

**Comment by fabiocav** [comment] 2020-01-07 01:43
Assigning this to be addressed in sprint 67

**Closed as completed** 2020-01-23 22:31 UTC

**Comment by kashimiz** [comment] 2020-01-29 23:51
Microsoft.Azure.WebJobs.Extensions v3.0.6 is now available on [NuGet.](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions/) This version references 
Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.14).

**Comment by SurushS** [comment] 2020-01-30 07:02
@kashimiz thank you for letting us know. And thanks for the quick pick up of the item. 😁
